### ISSUE TITLE
Update OpenChallenges app routes to use Ng v15 router

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1005]
See the example from this [article](https://blog.angular.io/angular-v15-is-now-available-df7be7f2f4c8).

**Comment by tschaffter** [comment]
@rrchai Let's define all the routes we need this month or the next one. Meanwhile, we can start using Angular v15 route API (see article above).

**Comment by rrchai** [comment]
focus on the router improvement of lazyLoad, or any other improvements from ng v15 can make app better. But if it's too complicate changes, make the conclusion here.

**Comment by tschaffter** [comment]
Moved to Sprint 23.02
