### ISSUE TITLE
Sort challenges by Closing soon, Starting soon

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1110]
Filter inspired by Kaggle.

- [x] #1130 
- [ ] Update OpenAPI description (@tschaffter )
- [x] #1157
- [x] #946 (@rrchai )

**Comment by tschaffter** [comment]
This ticket is a bit messy. Closing.

**Comment by tschaffter** [comment]
I'm reopening this ticket because I confused it with another one.

**Comment by rrchai** [comment]
Closed as all tasks are completed.
