### ISSUE TITLE
Identify the official name of the challenge registry

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1112]
We should settle on a name for the challenge registry for the private preview (2023 Q1) and before working on the app logo (#949).

Collecting ideas in [Challenge Registry Domain Names](https://docs.google.com/spreadsheets/d/1WXQ9wpYrg4XYP079qu0ImV8sOEYLUBfL1TItuucW77s/edit#gid=0)

We have used two names so far (see considerations below):

- Registry of Open Community Challenges (ROCC)
- Challenge Registry

## Considerations

- The domain name must be available (.com, .org, optionally .io?)
  - The domain name must include one token, i.e. no separator (preferable because easier to remember)
- Include the word "challenge" (preferably)
- About Registry of Open Community Challenges (ROCC)
  - Prefer a shorter name that is not an acronym?
  - Are "open" challenges too restrictive?
    - What is our definition of open challenges?
      - The challenge is open to anyone?
      - The challenge promotes open science (but does not enforce it as in DREAM challenges where participants can keep their submission private)
  - Common`rocc.*` domain names already taken

**Comment by tschaffter** [comment]
@chepyle @vpchung @rrchai @jaeddy @AmyHeiser @thomasyu888 @allaway @trberg @jaybee84 @echaibub

Your thoughts on the existing/new app name suggestions and considerations would be greatly appreciated to find a name that resonate with our team of challenge contributors.

As a reminder, the challenge registry aims to connect prospective participants and challenge organizers. For participants, this is a one-stop shop to find information about past, active and upcoming challenges and other users (participants and organizers).

For organizers, this is a hub where they can efficiently advertise their mission and challenges, and potentially gain insights about their challenge (e.g. list of registered/subscribed participants, profile of participants). These slides outlines some of the [problems and main use cases of the challenge registry](https://docs.google.com/presentation/d/1uo1ulSkjwDX2uJkjSi5XZVBXvKgZ2W0_5kmoTGdgFzQ/edit#slide=id.geb3904ae88_0_0).

**Comment by tschaffter** [comment]
Thanks @AmyHeiser for this ideas!

Hey Thomas, here are some thoughts, Kept the word challenge because I feel that is key, but then exchanged registry to be more of a centralizing idea:

    Challenge Hub - the most simple and straightforward
    Challenge Core
    Challenge Pivot Point 
    Challenge Entry Point
    Challenge Cornerstone
    Challenge Junction - sticking with the Synapse theme...

**Comment by vpchung** [comment]
Of those listed, I vote openchallenges.io or openchallenges.org -- descriptive yet still easy to say/type.

**Comment by AmyHeiser** [comment]
I like OpenChallenges too!  I didn't see that note before I listed more options :)

**Comment by thomasyu888** [comment]
Openchallenges

**Comment by tschaffter** [comment]
The official name of the project is now "OpenChallenges" (without space) and the domain name is openchallenges.io (we also bought openchallenge.io to cover our base). Thanks all for helping choosing the new name! 🎉
