### ISSUE TITLE
Add Challenge tagline

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1119]
The Challenge card includes a tagline in the challenge registry mockup. There are two strategy to capture this information:

- Add a dedicated property, e.g. `Challenge.tagline`
- Use the property `Challenge.description`

For context, I'm currently working on text search with Hibernate Search 6 and Elasticsearch. This work reminds me of the importance of accepting large descriptions (`Challenge.description`) in order to increase the relevance of text search results.

But there is still value in having a shorter tagline that fits into the challenge card. Hence this proposal:

1. If `Challenge.tagline` is specified, we use it in the Challenge card,
2. otherwise, we display the first N characters from `Challenge.description`.

That way, we don't absolutely need to come up with a tagline for all challenges, though this a tagline is probably a plus to capture the attention of the users.

How does this proposal sound? @vpchung @rrchai

**Comment by vpchung** [comment]
That sounds reasonable to me!

**Comment by tschaffter** [comment]
Actually maybe we are talking about a headline?

https://ambercreative.sg/blog/distinguishing-between-headlines-and-taglines

**Comment by tschaffter** [comment]
Here is a relevant article on consideration for an article headline and (meta) description.

https://seopressor.com/blog/google-title-meta-descriptions-length/

**Comment by vpchung** [comment]
So, following up on that article: will we be constraining the number of characters to 160 for `Challenge.description`?  And, if no headline is provided, then the challenge card will display up to 60 characters from `Challenge.description`?

**Comment by tschaffter** [comment]
> will we be constraining the number of characters to 160 for Challenge.description?

280 chars in the latest revision of this PR (#1123). I still had a thought about what you would like to do if the description we have in our existing challenge data is longer than 280 chars.

> if no headline is provided, then the challenge card will display up to 60 characters from Challenge.description?

Yes, that's what I propose to do.

**Comment by rrchai** [comment]
>If Challenge.tagline is specified, we use it in the Challenge card,
otherwise, we display the first N characters from Challenge.description.

@tschaffter This sounds good to me. 

> what you would like to do if the description we have in our existing challenge data is longer than 280 chars. We could increase this field (may make Google less happy and reduce the performance of challenge search request)

Truncate with ellipse? or can we lazy load/render the text?

One related question I have is where "ChallengeReadme" will stay in the Challenge page?

**Comment by tschaffter** [comment]
At this stage, the only reason for keeping the challenge readme would be to improve the performance of the text searches inside the challenge registry. However, I would not be able to quantify this improvement now and so would prefer to drop it and instead use the `description` property , which would indeed overlap with the readme if we were to keep both as you mentioned.

The other side of my reasoning is that the long description (readme) will be available on the challenge page after the user clicks on "Go to Challenge". Keeping only a shorter description in the registry guarantees that the user won't waste time reading duplicated long description.

Yet one benefit from hosting the long description on the registry could be for the sake of keeping a detailed record of past challenges whose challenge page on a given challenge platform may one day disappear.

For now we could keep it simple with a short description only.
