### ISSUE TITLE
Modify the DB CLI to push data to the project MariaDB instance

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1147]
Update the DB CLI to push data to the MariaDB instance (`http://challenge-registry-mariadb:3306`) instead of MongoDB.

**Comment by tschaffter** [comment]
Tentatively assigning this task to Verena.

**Comment by tschaffter** [comment]
@vpchung

A first step would be to push objects to one of the tables defined by the Challenge service. See `/workspaces/sage-monorepo/apps/challenge-registry/challenge-service/src/main/resources/db/migration/V1.0.0__create_tables.sql`.

Start the challenge service: `nx serve challenge-registry-challenge-service`

The challenge service takes care of starting the MariaDB instance. The challenge service is also responsible for 1) creating the tables required by the service and 2) populating the tables with example data when the service starts.

You can check the content of the SQL tables using the VS Code extension "SQLTools" included with the dev container.

When developing the DB CLI, you can regularly build it and execute it and see if the content of the tables have changed.

**Comment by tschaffter** [comment]
> **Note** Instead of using `localhost` to connect to a service, use the name of the service. For example to connect to the database: `jdbc:mysql://challenge-registry-mariadb:3306/challenge`.

**Comment by vpchung** [comment]
### Blocker
The `openchallenges-db-cli` shortcut is not running as expected, despite the original command working properly:

![Screen Shot 2023-02-03 at 11 25 39 AM](https://user-images.githubusercontent.com/9377970/216690698-ade76f6b-ec95-4402-8ab5-c82e5f269d0b.png)

After some digging, @tschaffter identified a missing component to the alias in `~/dev-env.sh`:

```
function openchallenges-db-cli {
  node dist/apps/openchallenges/db-cli/src/index.js "$@"
}
```

![Screen Shot 2023-02-03 at 11 30 20 AM](https://user-images.githubusercontent.com/9377970/216691036-01907cc2-b353-4e7c-97ee-f2fd0077708a.png)

We're now back in business! :tada:
