### ISSUE TITLE
Fix the appearance of the footer

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1149]
The footer seems to have reverted to an old/default font in the latest version of the app.

![image](https://user-images.githubusercontent.com/3056480/211423310-cc4d43c5-0660-484d-bcd5-c1d9618b2bdd.png)

Here are other potential modifications:

- Use the new name of the project (OpenChallenges)
- Remove the white margin around the footer
- Increase the size of the smallest font

**Comment by tschaffter** [comment]
Tentatively assigning to this sprint before the monthly sprint review (January 31st).

**Comment by vpchung** [comment]
> Remove the white margin around the footer

This surrounds the entire app (that is, it surrounds the navbar and main content as well), and I am not sure where it's coming from.  I'll look into it in a separate ticket.

**Comment by vpchung** [comment]
Ah okay, found the issue!  I can add the fix to this PR?
