### ISSUE TITLE
Sort by Recently Started and Recently Closed

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1207]
## Background

We have the following sorting strategies:

- `Relevance` (default): let the backend/Elasticsearch decide the order.
- `Recently Registered`: The way to be aware of the latest challenges that "came into existence".
- `Most Starred`: Sort challenges by "popularity".
- `Starting Soon`: Find challenges to participate in before they start.
- `Closing Soon`: Last chance to participate in a challenge before it closes.

Kaggle has additional sorting strategies, including these two that may be interesting:

- `Recently Launched`: These challenges have started and you can now participate in them!
- `Recently Completed`: Time to check the results! (there may be some delay before results are published after the end of the challenge).

@rrchai @vpchung Do you agree to add these two extra sorting strategies?

**Comment by tschaffter** [comment]
The above post prompt the following question: Do you remember what was the definition of `status: completed` and how is this value set? There are two options:

- Option 1: The maintainer of a challenge is responsible for setting the `status` of a challenge. This approach has the benefit that the challenge can be marked as completed after the challenge no longer accept submission, e.g. mark the challenge as completed after the publication of the results.
- Option 2: We automatically set the status depending on the start and end date. With this approach the maintainer does not have to maintain this property. They would still be responsible for maintaining the start and end dates.

@vpchung @rrchai @chepyle Thoughts?

**Comment by vpchung** [comment]
I'm not a huge fan of "Recently registered" -- it wouldn't be clear to me right away what is meant by "Registered".  Instead, can we maybe use "Recently added" or "Just added"?  I like "Recently Launched" and "Recently Closed"!

**Comment by vpchung** [comment]
> The above post prompt the following question: Do you remember what was the definition of status: completed and how is this value set?

Hmm... this is hard to say.  I like the idea of Option 2, however, that does require the organizers or maintainers to not only manage the timeline on their challenge-running platform of choice, but also on OpenChallenges as well.

Then again, that argument can also be applied to Option 1.... so again, hard to say.

**Comment by rrchai** [comment]
> I'm not a huge fan of "Recently registered" -- it wouldn't be clear to me right away what is meant by "Registered". Instead, can we maybe use "Recently added" or "Just added"? I like "Recently Launched" and "Recently Closed"!
+ 1
Since `Starting Soon`, `Closing Soon`, `Recently Launched`, `Recently Completed` can cover most time related sorting,  will the "Recently registered" filter be often used for users? One possible use case come into my mind is when the users would like to see the latest challenges without start date decided yet, but will the users be interested to check the challenges has no plan to launch yet? From my perspective, maybe we could consider to hold "Recently registered" sort for now until it's requested and other sort options are great!

**Comment by rrchai** [comment]
> Option 1: The maintainer of a challenge is responsible for setting the status of a challenge. This approach has the benefit that the challenge can be marked as completed after the challenge no longer accept submission, e.g. mark the challenge as completed after the publication of the results.
Option 2: We automatically set the status depending on the start and end date. With this approach the maintainer does not have to maintain this property. They would still be responsible for maintaining the start and end dates.

I think Option 2 is more reasonable. If the end date is passed, but the challenge is changed to "active", which might confuse the users, at least me. Thus, the maintainer of challenge would be better to change the close date to trigger the option 2.

> I like the idea of Option 2, however, that does require the organizers or maintainers to not only manage the timeline on their challenge-running platform of choice, but also on OpenChallenges as well.

I hope the openchallenges can interact with other platforms to auto update the start/end date _one day_.

**Comment by tschaffter** [comment]
> From my perspective, maybe we could consider to hold "Recently registered" sort for now until it's requested and other sort options are great!

I agree with you. We can keep remove it form the app while keeping it in the API.

**Comment by tschaffter** [comment]
Verera:

> The keyword "register" may have multiple meanings: 1) a participant register to a challenge, 2) register a challenge on OpenChallenges.
