### ISSUE TITLE
Search challenges with the search bar on the home page

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1236]
Most of the code needed for this feature should be available from the prototype.

1. The user enter search terms in the search bar.
2. The user press ENTER or click on the "Search" button.
3. The user is redirected to the challenge search page.
    - The search bar has been populated with the terms.
    - The other filters are in their default state.
    - The page shows results that match the search terms.

**Comment by rrchai** [comment]
refer to the ticket #1299 using query param
