### ISSUE TITLE
[Story] Add all the DREAM Challenges already collected to OpenChallenges DB

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1249]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a user of the private preview, I want to see that several organizations have committed to publish their data in OpenChallenges so that I can trust that I can use this app to find completed, active and upcoming challenges.

### Description

Add all the DREAM challenges already collected (DREAM landscape) to the OpenChallenges DB. Contribute to the development of the data model to ensure that the data can be correctly captured and shows in OpenChallenges.

### Acceptance criteria

- All the DREAM challenges that are part of the current DREAM Landscape are visible from the challenge search page.
- All the challenge metadata required to create a the challenge card have been added to the DB.
- All the challenge metadata required to populate the challenge profile page have been added to the DB.

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Verena:
- Added all the DREAM challenges to the DB already, missing the input data type
- Done using directly SQL data, not using the CLI

**Comment by vpchung** [comment]
Update: CLI is complete and can populate the database with all challenges listed in the [OC schema](https://docs.google.com/spreadsheets/d/1XRSUVqbZk_k9_rV1vpgPVMQ0fVV0mavwY8Aqyy0C2HQ/edit#gid=1834177142)

**Comment by tschaffter** [comment]
We should keep this story open until we have finalized the Challenge schema and its relationship with Organization. I should be able to unblock this work next week.

**Comment by tschaffter** [comment]
Closing this issue since the DREAM challenges are now in the DB. The data model will be slightly adapted next months to accommodate addition features (e.g. filter challenges by org), but the bulk of bring the data to the DB for the private preview should be done.
