### ISSUE TITLE
[Story] Update the routes of the Challenge Registry pages

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/sage-monorepo#1267]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a user, I want to be taken to the desired page as what I type in the search bar of browser.

### Description

Refer to #997 

### Acceptance criteria

- [x] #1370
- [x] #1340 (backend)
- [x] Update the routes for the pages following the format `/{profile-type}/{profile-slug}`:
  - ~~`/challenge/{challenge-slug}`~~ `/challenge/:challengeId/:challengeSlug`
  - `/org/{organization-slug}`
  - `/user/{user-slug}`
- [x] Update the routes of each page to ensure the redirection to `/not-found` if invalid url/slug.

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by rrchai** [comment]
`/challenge/:challengeId/:challengeSlug`:  `challengeSlug` is optional, but `challengeId` is required.

**Comment by tschaffter** [comment]
@rrchai

- `/challenge` -> `/challenge`
- `/org` -> `/org`
- Any API error -> `not-found`
  - Only when navigating to the page of an entity like a challenge or org. On the search page for example, show the message in the snack bar as you already do for one type of error.

**Comment by rrchai** [comment]
> /challenge -> /challenges
/org -> /orgs
Any API error -> not-found

^ is the redirecting destination when the left url is searched. For example. if user enters the `/challenge`, it will be redirected to `/challenges` (challenge search page).

>Only when navigating to the page of an entity like a challenge or org. On the search page for example, show the message in the snack bar as you already do for one type of error.
It's doable, but I don't think it's helpful for end-users, as users might not be able to see the snack bar before it's redirected to `not-found` page very quickly.

**Comment by tschaffter** [comment]
We should use `/challenge` and `/challenge/<id>` - no `/challenges` - for the sake of keeping URLs short as motivated in the Google doc.

> It's doable, but I don't think it's helpful for end-users, as users might not be able to see the snack bar before it's redirected to not-found page very quickly.

The error should at least also be printed in the browser console. We can discuss if the snack bar is the right way to show the error or if we want to print it on the page.

We really need users to let us know when they experience issues. Hopefully the monitoring system I started to put in place will also alert us. We should actually really distinguish between "not found" and error. So for now no redirection to not found but instead show the error.

**Comment by rrchai** [comment]
>We should use /challenge and /challenge/<id> - no /challenges - for the sake of keeping URLs short as motivated in the Google doc.

To clarify, the url for challenge profile will be using `/challenge/<id>`, but when the user enter `/challenge` without any ids by accident, we are redirecting to the challenge search page: `/challenges`.

>The error should at least also be printed in the browser console. We can discuss if the snack bar is the right way to show the error or if we want to print it on the page.

Yes, the error will be recorded in the console.

>We really need users to let us know when they experience issues. Hopefully the monitoring system I started to put in place will also alert us. We should actually really distinguish between "not found" and error. So for now no redirection to not found but instead show the error.

I agree. We could create subcomponents for `not-found` (i.e `not-found-challenge` or `not-found-org`) to show more appropriate messages for users.

**Comment by tschaffter** [comment]
> To clarify, the url for challenge profile will be using /challenge/<id>, but when the user enters /challenge without any ids by accident, we are redirecting to the challenge search page: /challenges.

I was thinking that the search page could be `/challenge`, not `/challenges`.

**Comment by rrchai** [comment]
> I was thinking that the search page could be /challenge, not /challenges.

@tschaffter Oh okay! That now makes sense to me - sorry for the misunderstanding.

**Comment by tschaffter** [comment]
Added to Sprint 23.03
