### ISSUE TITLE
Make the footer sticky at the bottom

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/sage-monorepo#1270]

**Comment by tschaffter** [comment]
I believe that this footer is [sticky](https://github.com/tschaffter/PHCCollaborationPortal/tree/develop/client/components/footer).

**Comment by tschaffter** [comment]
@rrchai I believe that the [Agora footer](https://github.com/Sage-Bionetworks/Agora/tree/develop/src/app/core/components/footer) is sticky so that could be another example and a good use case of partial reuse of a component developed at Sage.
