### ISSUE TITLE
[Story] Design an organization card for the organization search page

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1271]
We are going to create a search page for organizations and need to create a component that represent an organization. We have an org "card" that uses the avatar component, but this format likely restrict too much the amount of information we want to put in that item. The goal of this ticket is actually to:

- [x] List the information that we want to include for each org item listed in the org search page
- [x] If the existing org "card"/avatar does not meet the above requirement, design a new component in Figma

**Comment by vpchung** [comment]
First design idea for organization card:

![Image](https://user-images.githubusercontent.com/9377970/220843509-9cea44db-ee55-43e2-a78f-5b04d48d2644.png)

The footer would be the total number of challenges supported, let it be by organization, sponsorship, and/or data contribution.

**Comment by tschaffter** [comment]
The card looks great! Here is my feedback:

- "+N other users": replace "users" by "members" in case we want to add people who are not yet users. "members" would also work if we decide to list only registered users.
- Description: What about removing this description to simplify the data collection and declutter the search page? If the user don't know the org, it's a good opportunity for them to learn more about this org by visiting their page on OC.
- In the future we could show the tags directly assigned to the org or indirectly linked to it by looking at the tag that appear the most frequently on the pages of the challenges the org supports.

**Comment by rrchai** [comment]
Thanks for the design. I like you have included # of members and # of connected challenges, which I think they are helpful info to explore organizations. One concern I have is whether we could get the banner info of organizations. I feel using the avatar is enough for the organization.

**Comment by vpchung** [comment]
Thank you for feedback!   I mostly tried to stick with the same layout & design for the challenge card, but I agree with you both regarding the descriptions and banner pictures.  Here's the next iteration with implementations of the feedback:

![Screen Shot 2023-02-23 at 10 21 51 AM](https://user-images.githubusercontent.com/9377970/220996995-0c710f31-bf9c-4aef-b942-a6f22742f901.png)

**Comment by tschaffter** [comment]
@vpchung Can you please add a link to the Figma doc before closing the issue?

**Comment by vpchung** [comment]
[Link to design on Figma](https://www.figma.com/file/yAeIrg6Whc8Bqj2EnG4MWP/Challenge-Registry?node-id=17%3A115&t=w3nChO86081V5Xlx-0)

Closing now!
