### ISSUE TITLE
Identify organization contribution types

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1276]
There are different way - or type of contribution - that an organization can make during the lifetime of a challenge. We want to capture these types of contributions to answer queries such as:

- What are the organizations that provided cloud compute support?
- What are the orgs that provided data to challenge with input data type "genomic"?

In the current data model (see [lucid](https://lucid.app/lucidchart/1544f8ff-6335-4ae6-beba-c761e2fba094/edit?page=KL-om_guQqEK&invitationId=inv_669c06d8-cd73-46bf-a896-dccd8bb2c593#)), this information is captured as `ChallengeOrganizationRole`. Proposed values are:

- `challenge_organizer`: what I referred recently as "organization steward" (I believe @chepyle was the first to use this term?)
- `cloud_contributor`
- `data_provider`
- `scientific_contributor` (or `scientific_advisor`?)

<img width="751" alt="image" src="https://user-images.githubusercontent.com/3056480/216734406-9e93d392-d050-4a94-933b-628f4514a53b.png">

Also, what do you think about renaming this enum from `ChallengeOrganizationRole` to `ChallengeContributionRole` or `ChallengeOrganizationType` to enable us to capture contribution made by non-organizer, mainly participants. Here I'm thinking about capturing at some point organizations who submitted solutions to challenges. 😊

For example, the IBM org page could include the following sections:

- Challenges that IBM supported as cloud provider
- Challenges that IBM supported as scientific advisor
- Challenges that IBM contributed to as participant

The goal of this ticket is to curate the above list of contribution type so that we can enable filtering org by contribution type (#1252).

**Comment by vpchung** [comment]
Contribution roles have been captured [here](https://docs.google.com/spreadsheets/d/1XRSUVqbZk_k9_rV1vpgPVMQ0fVV0mavwY8Aqyy0C2HQ/edit#gid=1850756043), using the values:

* challenge_organizer
* data_contributor
* sponsor

Previous curation efforts did not capture cloud or scientific contributions.  If these are desired, I will add a ticket for this curation effort.
