### ISSUE TITLE
Add "notebook" to type of submissions

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1297]
Most/all Kaggle challenges will use this data type (Jupyter notebooks).

**Comment by vpchung** [comment]
Ah, looks like I'll need to brush up on my OpenAPI commands 😅

**Comment by vpchung** [comment]
TODOs:
- [ ] add to openapi spec
- [ ] add to table schema
- [ ] update OC schema to use "notebook" instead of "other" for Kaggle challenges

**Comment by tschaffter** [comment]
Useful command:
- `nx run openchallenges-api-description:build`
- `nx run openchallenges-challenge-service:openapi-generate` to update the challenge service. No more actions should be required to update the Java code as you are extending an existing Enum.

**Comment by vpchung** [comment]
@tschaffter exactly what I needed - thanks for the impromptu cheat sheet!
