### ISSUE TITLE
[Story] Sort organizations by their number of challenges supported (backend)

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1331]
The goal is to update the organization object returned by the backend to include the number of challenges an org has contributed to.

## Tasks

- [x] #1356
- [x] #1358

> **Note** We need to be careful about not counting a given challenge more than once if the org contributed to it with more than one role.

**Comment by vpchung** [comment]
> Update challenge export script to save Organization.challengeCount

Tracking in #1356
