### ISSUE TITLE
[Story] Identify Terms and Conditions

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1351]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a user, I want to know what are the Terms and Conditions of OpenChallenges so that I can identify whether I can use this app.

### Description

Identify the Terms and Conditions for OpenChallenges in collaboration with the Governance team. Hopefully we can reuse the terms and conditions from another Sage app or start from a template and customize it.

### Acceptance criteria

- The terms and conditions are approved by Thomas, Jake and the Governance team.

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by vpchung** [comment]
Similar to #1360, I was able to use Termly to play-generate a Terms Of Use policy:

![Image](https://user-images.githubusercontent.com/9377970/233512492-b13cd75e-a53c-4256-ad25-7c0c2aec8ada.png)

![Image](https://user-images.githubusercontent.com/9377970/233512493-3b95e091-89b8-4e1c-b25d-0f64238ada52.png)

Important things to identify in our own policy include:

* platform type (website vs mobile app)
* general platform information (URL, hosting location, etc.)
* platform content (ie, can users post content?)
* how disputes will be handled
* industry-specific compliance
*

**Comment by vpchung** [comment]
#### 4/21 Update:
I reached out to governance over Slack (conversation starts [here](https://sagebionetworks.slack.com/archives/C6TDG5UE5/p1682094065267949)), and I think this will require more effort than initially planned.   Specifically, we will need to identify how the OC will differ from Synapse (and other OneSage platforms).  Additionally, the Sage legal team will/may? need to be looped in.

FWIW, Ann did share the [current Synapse Terms & Conditions](https://s3.amazonaws.com/static.synapse.org/governance/SageBionetworksSynapseTermsandConditionsofUse.pdf?v=5) as a starting point.

**Comment by vpchung** [comment]
Adding @chepyle and @tschaffter to the ticket, as their involvement will also be needed for this effort.

**Comment by vpchung** [comment]
#### 4/25 Update:

Chatted some more with Hayley from governance and she suggests @chepyle and @tschaffter officially reach out to governance regarding this, as this could be tied to Christine's effort of revamping the Synapse policies to One Sage.  And, if the timeline doesn't fit, then she may have another solution.

(I'll be removing myself from this ticket now.)

**Comment by tschaffter** [comment]
## Update

- Adding to May sprint

**Comment by tschaffter** [comment]
Added to Sprint 23.06

**Comment by tschaffter** [comment]
The Terms of Service are available [here](https://sagebionetworks.jira.com/wiki/spaces/OA/pages/2948333575/OpenChallenges+Terms+of+Use).
