### ISSUE TITLE
[Story] Instantiate an ALB and EC2 instance to deploy OC

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1352]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a participant to the private preview, I want to access OC web client so that I can test the app and provide feedback to the OC team.

### Description

For the private preview, the OC stack will be deployed on a single EC2 instance. The ALB in front of the instance is to enable HTTPS and configure our domain name (openchallenges.io).

Once the EC2 is instantiated, the OC stack will be deployed with `git clone` + manual configuration (once) + docker compose.

There are two approaches:

- Create the ALB and the EC2 instance manually
- Create the ALB and the EC2 instance with a CloudFormation template

The second would be preferable but would require more story points.

### Acceptance criteria

- The ALB and EC2 instances have been instantiated.
- We can SSH to the EC2 instance
- The port 8080 of the EC2 instance is open to the ALB.
- The ALB is configured so that it sees the EC2 instance as "healthy".
- A client can access a simple HTTP server running on the EC2 instance via the ALB.

Out of scope:

- Deployment of the app on the EC2 instance.
- Configuration of the domain name.

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by thomasyu888** [comment]
@tschaffter There are a few things you must do.  You can leverage this github repo: https://github.com/Sage-Bionetworks-Challenges/cnb-aws-infra.

1. You should set up OIDC integration like this: https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/749/files.  This will allow for CI/CD to deploy your stack
2. Heres the template for ALB-HTTPS: https://github.com/Sage-Bionetworks/aws-infra/blob/master/templates/managed-alb-https-v2.yaml.  You would use is as a configuration in your sceptre config.  
3. Here is a template for EC2: https://github.com/nlpsandbox/nlpsandbox-infra/blob/main/templates/nlpsandbox.yaml.

My advise is to post in the sageit slack channel to get assistance.

**Comment by brucehoff** [comment]
I would like to challenge the suggestion/assumptions:
>  the OC stack will be deployed on a single EC2 instance.
and
> We can SSH to the EC2 instance

Today Sage has a mature solution in which an app' can be deployed to ECS behind a load balancer.  The solution happens to use AWS Fargate, so there is no EC2 instance to ssh into, nor is there any need to do so:  Configuration can be either passed in during CloudFormation set up or (for sensitive information) through AWS Secrets Manager.  Performance and logs are collected and viewed in AWS CloudWatch.  

The only limitation is that the application runs as a single container.  I would like to discuss how to extend the current solution to support a more general case, a useful superset of the "OC" case.

**Comment by brucehoff** [comment]
@tschaffter Have you spoken with our information security officer about what is required when making software available on the web, outside of Sage?  He has an 'operational readiness review' questionnaire that has been used elsewhere.

**Comment by tschaffter** [comment]
> Have you spoken with our information security officer about what is required when making software available on the web, outside of Sage? He has an 'operational readiness review' questionnaire that has been used elsewhere.

@brucehoff This is a good suggestion and I should fill in this questionnaire. For now I don't plan to share the app outside of Sage and I'm looking for a simple and/or ready-to-be-used method to deploy one EC2 with a port open so that I can expose our web app.

> Today Sage has a mature solution in which an app' can be deployed to ECS behind a load balancer. 

Is there a document that describes this solution (e.g. with a list of known limitations)?

**Comment by tschaffter** [comment]
Bruce shared the following resource today, which we could maybe use to deploy the OC stack to AWS using Docker Compose.

> I was reading your [presentation](https://docs.google.com/presentation/d/1X8RaMYnSPD8Cv8QNK4pSgE6qHZDTNjQ2qoGqP7d3Kbo/edit#slide=id.g1938a38a2b0_0_0) in which you talk about deploying the Challenge Registry “at scale” in 2Q2023.  I recall that the system is defined using Docker Compose.  I wonder if you have seen this blog, which talks about using Docker Compose to deploy to AWS ECS: https://aws.amazon.com/blogs/containers/deploy-applications-on-amazon-ecs-using-docker-compose/

**Comment by thomasyu888** [comment]
I just remembered, this might not matter for the test deployment but... For the production deployment, if you have a database layer for your application, I think it might be safest to have a persistent database deployment.

This way you prevent potential loss of information if the database layer is just deployed on an ec2.

**Comment by brucehoff** [comment]
Thank you for your comments, @tschaffter .

> and a secret vault (HashiCorp Vault).

Can we use AWS Secrets Manager when deploying the application to AWS? If we do this then AWS Config / SecurityHub can help make sure we are storing secrets securely.

**Comment by tschaffter** [comment]
@brucehoff Yes, it seems that Spring Cloud Config server supports [AWS Secrets Manager as a config data source](https://www.baeldung.com/spring-cloud-config-without-git#4-secrets). Below is the current sources that we use during development.

![image](https://user-images.githubusercontent.com/3056480/228049167-e17bc241-3a49-45c7-96f0-45936e5343de.png)

**Comment by tschaffter** [comment]
The OC stack is currently deployed on an EC2 so closing this ticket. In the future, we will progressively migrate the components of the OC stack to use AWS Fargate whenever possible
