### ISSUE TITLE
[Story] Identify Privacy Policy

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1360]
The goal is to identify the privacy policy for OC.

Related tasks:

- #994

**Comment by vpchung** [comment]
I found a generator called [Termly](https://termly.io/products/) that let me test out creating a Privacy Policy.  Here is a small snippet of what I was able to generate with their service:

![Image](https://user-images.githubusercontent.com/9377970/233510699-309b06ab-ff27-41a3-a904-6b9fcbb85a55.png)

![Image](https://user-images.githubusercontent.com/9377970/233510750-a98b0f98-129d-4b4f-b7e4-ecaded761901.png)


Based on the questions Termly asked, the things we'll need to identify in our Privacy Policy are:

* who is our user base?
    * user location (depending on where they're located, we'll have to be compliant with CCPA, CDPA, GDPR, etc)
    * user age (is our target audience under 18?)
    * user accounts (can they create accounts?  can they update/delete accounts themselves?)
* type of personal information collected
    * this includes derivative data, such as tracking data collected by Google Analytics
* use of the collected information, such as provision of services, marketing, promotions, etc.
* disclosure of information, i.e. will we share the information with third-parties, business affiliates, etc.
* use of tracking technologies, such as cookies (required by EU and UK)
    * if using cookies, we'll need a cookie policy 
* who users should contact about their information, e.g. designated DPO? Or maybe just our team in general.
* user rights, aka how can users contact us to modify their information

**Comment by vpchung** [comment]
#### 4/21 Update:
I reached out to governance over Slack (conversation starts [here](https://sagebionetworks.slack.com/archives/C6TDG5UE5/p1682094065267949)), and I think this will require more effort than initially planned.   Specifically, we will need to identify how the OC will differ from Synapse (and other OneSage platforms).  Additionally, the Sage legal team will/may? need to be looped in.

From @chepyle :

> In our discussions with legal and governance we’ll have to explain what data we’ll collect and why this is different from the other portals

FWIW, Ann did share the [current Synapse Privacy Policy](https://s3.amazonaws.com/static.synapse.org/governance/SynapsePrivacyPolicy.pdf?v=5) as a starting point.

**Comment by vpchung** [comment]
Adding @chepyle and @tschaffter to the ticket, as their involvement will also be needed for this effort.

**Comment by vpchung** [comment]
#### 4/25 Update:

Chatted some more with Hayley from governance and she suggests @chepyle and @tschaffter officially reach out to governance regarding this, as this could be tied to Christine's effort of revamping the Synapse policies to One Sage.  And, if the timeline doesn't fit, then she may have another solution.

(I'll be removing myself from this ticket now.)

**Comment by vpchung** [comment]
I misspoke -- it's actually 10,000 views!  But regardless, I agree that we should host the policy directly on our app instead of using a third-party.

**Comment by tschaffter** [comment]
Upgrading to Story so that it's on par with #1351

**Comment by tschaffter** [comment]
## Update

I reached out to Hayley. She plan to share a draft next week. We should have the document ready in 3-4 weeks.

**Comment by tschaffter** [comment]
Added to Sprint 23.06

**Comment by tschaffter** [comment]
The Privacy Policy is available [here](https://sagebionetworks.jira.com/wiki/spaces/OA/pages/2948530178/OpenChallenges+Privacy+Policy).
