### ISSUE TITLE
Use constructor injection instead of field injection in Java code

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1392]
I recently started to replace field injections by constructor injection as recommended in several articles. The goal of this task is to replace the remaining field injections used in the active components/services in Java.

- https://medium.com/@toxicdev/field-injection-v-s-constructor-injection-dd9db2d85b7b
- https://sensei.securecodewarrior.com/recipes/Field_injection_is_not_recommended_lombok

## Components

- [x] Image service
- [x] Challenge service
- [x] Organization service
- [x] API Gateway
- [x] Config server

**Comment by tschaffter** [comment]
@mdsage1 This task would provide a good introduction to the concept of field vs constructor injection in Java microservices.

**Comment by tschaffter** [comment]
Added to Sprint 23.06

**Comment by tschaffter** [comment]
Return to Backlog

**Comment by tschaffter** [comment]
## Update 2023-08-31

Maria didn't have time to contribute to this issue this sprint.

**Comment by tschaffter** [comment]
Added to Sprint 23.09

**Comment by mdsage1** [comment]
Api-Gateway doesn't use field injection. Config-server doesn't use field injection.There were no changes made to either.
