### ISSUE TITLE
[Story] Collect the logo images of the organizations

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1411]
### What projects is this story for?

OpenChallenges

### As a user, I want

TBD

### Description

The goal of this story is to:

- define guidelines for the collection and preparation of the logo images
- download the logo of all the organizations included in the data
- add the logos to the AWS S3 bucket `openchallenges-img` inside the folder `img/logo/`
- keep track of the key of the logo (e.g. `img/logo/ibm.png`)
- update the value of `Organization.avatarUrl` in the OC data with the logo object keys

### Acceptance criteria

TBD

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
@vpchung is working with Stockard to create a organization logo placeholder.

**Comment by vpchung** [comment]
Something I found helpful as I'm going through this process:

1. Click on the link in `website_url` to open the website and find info about the organization's description + contact info (if any).  This also helps ensure the URL is still correct -- I've come across a couple of instances where the URL was broken/did not link to the correct org
2. Enter the name of the org + "twitter".  If the org has a twitter account, they most likely have a square avatar that is hi-def.
3. If they don't have a twitter account, then I would try right-clicking on the website brand image to see if I could open the image in a new tab.
4. If there isn't an image available from their website, I would then look at what is available in Google search and/or Wiki.

**Comment by tschaffter** [comment]
@vpchung Thanks for the great tips. Here are some thoughts:

- I'm wondering whether Thumbor supports SVG and if yes, if they are convenient to be used.
  - SVG are "lossless" and their file size is lower than bitmap images, thus resulting in smaller loading times. IF Thumbor makes it easy to use SVG images, then we should prefer collecting an SVG image.
  - I believe that Thumbor can do image conversion, e.g. PNG to JPG. If working with different file formats makes things complicated, we could explore converting to PNG (supports transparent background). I'm wondering whether the conversion from SVG to PNG works.
- Ideally we should stick to logos officially provided by organizations instead of trying to find a logo at all cost.
  - There are organizations that have very strict guidelines about how their logos should be used.
  - I would consider Wikipedia as a trustworthy source for finding logos.
  - I've found several organization logo on Wikipedia to be available in SVG format.

**Comment by vpchung** [comment]
> I'm wondering whether Thumbor supports SVG

I want to say yes, as I've uploaded a couple of SVG files and am able to access them, e.g.

![Screen Shot 2023-04-26 at 11 05 43 AM](https://user-images.githubusercontent.com/9377970/234664535-ec5e9b29-9eb8-48c5-adf3-3a7f44f9289f.png)

I agree that SVG should be highest priority, but in the interest of time, I grabbed whatever was available from Twitter/LinkedIn, which was usually PNG.

> I believe that Thumbor can do image conversion... I'm wondering whether the conversion from SVG to PNG works.

I just tried to do a conversion using [`filter`](https://thumbor.readthedocs.io/en/latest/format.html) and (I think?) it worked:

![Screen Shot 2023-04-26 at 11 14 16 AM](https://user-images.githubusercontent.com/9377970/234666366-ae203e19-210b-4001-af67-c5dedb4c1022.png)


> There are organizations that have very strict guidelines about how their logos should be used.

Oh that's a very good point.  I did not think to look for those policies as I was browsing the websites.

**Comment by tschaffter** [comment]
> Oh that's a very good point. I did not think to look for those policies as I was browsing the websites.

That's totally fine! If the logo comes from a "trusted" source they it should meet the requirements of the org. It's also OK if we have already collected a few logos from "untrusted" sources: orgs could always contact us if they want to use a different logo.

**Comment by tschaffter** [comment]
@vpchung I will take you on your kind offer to collect the logo that were initially assigned to me. 🙏

**Comment by vpchung** [comment]
@tschaffter okay dokes, I'm on it.

**Comment by vpchung** [comment]
#### 5/1 Update

197 out of 238 logos have been collected and added to the S3 bucket.  The db has also been updated to populate `avatarUrl` with the objectIds.

**Comment by tschaffter** [comment]
The remaining logos have been added to S3.
