### ISSUE TITLE
[Story] Enable to search org by searchTerm in the dropdown widget

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/sage-monorepo#1421]
### What projects is this story for?

OpenChallenges

### Description

The current search field and dropdown on the widget come together using the existing component from primeng ([MultiSelect](https://primeng.org/multiselect)). The search field will only filter the label of options. We would like to utilize the search field to filter the organizations by `searchTerm`.

As @tschaffter purposed, the widget should behave like below:
- The user starts typing in the widget search field. 400 ms after the user stopped typing, a request is sent to the org service to find orgs that match the search terms.
- The widget receives a list of orgs based on the search terms. The list of orgs in the widget is updated.

### Acceptance criteria

- the org can be filtered by the search term in the dropdown

### Tasks

- #1423 

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Here is the extended workflow:

1. The user activates the filter widget. The search field is empty and the full list of organizations is shown. For now it's OK to get this list with a single request to the org service but in the future we should use pagination when the number of orgs is larger than the max page size.
2. The user starts typing in the widget search field. 400 ms after the user stopped typing, a request is sent to the org service to find orgs that match the search terms.
3. The widget receives a list of orgs based on the search terms. The list of orgs in the widget is updated.
4. The user select an org. We use the id of the org to send a search query to the challenge service and we update the results.

**Comment by rrchai** [comment]
The task is converted to story since it requires more work than a task.

**Comment by tschaffter** [comment]
Added to Sprint 23.05

**Comment by tschaffter** [comment]
Added to Sprint 23.06
