### ISSUE TITLE
[Bug] Vault crashes at startup because of an out-of-memory issue

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What projects are you seeing the problem on?

OpenChallenges

### Current behavior

@mdsage1 and I noticed that Vault failed to started inside her devcontainer because of an out-of-memory issue. Raising the max memory to 500M solved the issue.

### Expected behavior

Vault container should be healthy.

### Anything else?

@mdsage1 Can you confirm that your instance has 16 GB of memory? For some reason 200M works fine for me.

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mdsage1** [comment]
I am using 80GB of memory @tschaffter

**Comment by tschaffter** [comment]
@mdsage1 You are probably referring to your storage and not the memory (RAM).
