### ISSUE TITLE
[Bug] Fix invalid challenge slugs

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What projects are you seeing the problem on?

OpenChallenges

### Current behavior

Example: `http://localhost:4200/challenge/oropharynx-cancer-%28opc%29-radiomics-challenge-::-human-papilloma-virus-%28hpv%29-status-prediction`

The slug format is defined in the API description but is not enforced at the database level, which this ticket could address.

### Expected behavior

The challenge slug example posted above should include only lowercase a-z, 0-9 and dash as a separator (see slug format defined in the API description).

### Anything else?

This behavior is observed in the PR #1433.

### Commit ID

e977cb95cbacb9d1e46cd34660fec99317ec5348

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vpchung** [comment]
Whoops, thank you for that catch!!

Kaggle has their own slugs, which I accidentally overwritten -- will revert that change now.
