### ISSUE TITLE
[Story] Collect UI/UX feedback from Sage Design (Adam)

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1455]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a user, I want the UI/UX of OpenChallenges to be slick and intuitive to use so that I can easily perform the tasks that I need to do.

### Description

TBD (@vpchung )

### Acceptance criteria

TBD (@vpchung )

### Tasks

TBD (@vpchung )

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
@vpchung suggest to ask Adam to test the app once it's deployed on AWS.

**Comment by tschaffter** [comment]
Added to Sprint 23.06

**Comment by tschaffter** [comment]
Move to Sprint 23.07

**Comment by vpchung** [comment]
## 7/13 update

With [the app](https://dev.openchallenges.io/) having just deployed, I have reached to Adam via Slack to get his feedback on the UI/UX.

**Comment by vpchung** [comment]
^ we will be meeting next week to discuss - stay tuned!

**Comment by vpchung** [comment]
[Tickets](https://github.com/orgs/Sage-Bionetworks/projects/39/views/18?filterQuery=status%3ABacklog+Enhancement%5D) have been created for each of the points, where we can further discuss whether the enhancement should be addressed.

Closing this ticket now.
