### ISSUE TITLE
[Bug] Unable to load images from image-service

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#1469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What projects are you seeing the problem on?

OpenChallenges

### Current behavior

On my end, I am not able to connect the app to the image-service:

![Screen Shot 2023-04-25 at 3 35 31 PM](https://user-images.githubusercontent.com/9377970/234419038-5cc643a1-d0ba-4a84-a58c-d586ec6c0378.png)

In the console log, I get a 400 bad request:
![Screen Shot 2023-04-25 at 3 36 53 PM](https://user-images.githubusercontent.com/9377970/234419133-ebef276f-3741-4236-b13f-7108c50ecf86.png)

Perhaps I am missing a container?  Here are the current running containers on my end:
```
$ docker ps
CONTAINER ID   IMAGE                                                        COMMAND                  CREATED       STATUS                PORTS                              NAMES
59be6c087df3   sagebionetworks/openchallenges-api-gateway:latest            "/cnb/process/web"       2 weeks ago   Up 8 days (healthy)   0.0.0.0:8082->8082/tcp             openchallenges-api-gateway
ef6cc4c505d9   sagebionetworks/openchallenges-image-service:latest          "/cnb/process/web"       2 weeks ago   Up 8 days (healthy)   0.0.0.0:8086->8086/tcp             openchallenges-image-service
907b75eed1af   sagebionetworks/openchallenges-challenge-service:latest      "/cnb/process/web"       2 weeks ago   Up 8 days (healthy)   0.0.0.0:8085->8085/tcp             openchallenges-challenge-service
1db606f9872f   sagebionetworks/openchallenges-organization-service:latest   "/cnb/process/web"       2 weeks ago   Up 8 days (healthy)   0.0.0.0:8084->8084/tcp             openchallenges-organization-service
ed828160deba   sagebionetworks/openchallenges-service-registry:latest       "/cnb/process/web"       2 weeks ago   Up 8 days (healthy)   0.0.0.0:8081->8081/tcp             openchallenges-service-registry
1ae87f830475   sagebionetworks/openchallenges-config-server:latest          "/cnb/process/web"       2 weeks ago   Up 8 days (healthy)   0.0.0.0:8090->8090/tcp             openchallenges-config-server
94251032f067   sagebionetworks/openchallenges-elasticsearch:latest          "/bin/tini -- /usr/l…"   2 weeks ago   Up 8 days (healthy)   0.0.0.0:9200->9200/tcp, 9300/tcp   openchallenges-elasticsearch
9e2220d2aa2e   sagebionetworks/openchallenges-thumbor:latest                "tini -- /docker-ent…"   2 weeks ago   Up 8 days (healthy)   0.0.0.0:8889->8888/tcp             openchallenges-thumbor
4455f925146e   sagebionetworks/openchallenges-vault:latest                  "docker-entrypoint.s…"   2 weeks ago   Up 8 days (healthy)   0.0.0.0:8200->8200/tcp             openchallenges-vault
5984607deb21   sagebionetworks/openchallenges-elasticsearch:latest          "/bin/tini -- /usr/l…"   2 weeks ago   Up 8 days (healthy)   9200/tcp, 9300/tcp                 openchallenges-elasticsearch-node-2
c4e880efed1b   sagebionetworks/openchallenges-elasticsearch:latest          "/bin/tini -- /usr/l…"   2 weeks ago   Up 8 days (healthy)   9200/tcp, 9300/tcp                 openchallenges-elasticsearch-node-3
a9b8dd1992c4   sagebionetworks/openchallenges-zipkin:latest                 "start-zipkin"           2 weeks ago   Up 8 days (healthy)   9410/tcp, 0.0.0.0:9411->9411/tcp   openchallenges-zipkin
f2b8c0e75bc7   sagebionetworks/openchallenges-mariadb:latest                "docker-entrypoint.s…"   2 weeks ago   Up 8 days (healthy)   0.0.0.0:3306->3306/tcp             openchallenges-mariadb
```

### Expected behavior

I expect to be able to load images saved in our S3 bucket, much like what is showcased in this [PR](https://github.com/Sage-Bionetworks/sage-monorepo/pull/1452#issue-1654196176).

### Anything else?

FWIW, I'm also not able to load http://localhost:8082/img/unsafe/triforce.png as suggested by [this doc](https://github.com/tschaffter/sage-monorepo/blob/main/apps/openchallenges/thumbor/README.md) either (but I can access http://localhost:8889/unsafe/600x600/triforce.png just fine).

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
There may be more than one things going on:

- The object key that you specify is `triforce.png` and I would expect this key to work. I just tried using the main branch and I can get an image URL from the image service. Then I can use this URL to get the image from Thumbor. Here is what I did:
  - Go to the image service Swagger UI: http://localhost:8086
  - Get an image URL for the key `triforce.png`
  - The image URL returned is `http://localhost:8889/ucBCtKeFXF3rPUsmUGmxcTRnoj0=/300x300/triforce.png`
  - The image is shown when opening this URL in the browser.
- Another issue I bumped into is that object keys that includes a `/` like in `logo/nih.png` does not work because the object key is currently passed to the image service as a path parameter. Here the REST API interprets the request as pointing to an endpoint that does not exist (this is not surprising). Specifying the object key via a query or body parameter would be the way to solve this issue. I will open a PR.

I will now start exploring these issues.

**Comment by vpchung** [comment]
> I just tried using the main branch and I can get an image URL from the image service.

How interesting.  I'm in the main branch as well, but cannot get the image to show.  The URL you pasted is the same that is throwing me a 400 error in the console log.  I also tried to access the URL to no avail:

![Screen Shot 2023-04-25 at 4 13 09 PM](https://user-images.githubusercontent.com/9377970/234427372-cd1cbf2b-b09d-4218-9b07-41e8778c4f30.png)

**Comment by tschaffter** [comment]
Rebuilding the dev container should open the port used by the image service.

**Comment by vpchung** [comment]
Thanks, @tschaffter - rebuilding the devcontainer did resolve the issue with the missing port.  But sadly, still can't load the image (neither in the app nor by going to `http://localhost:8889/ucBCtKeFXF3rPUsmUGmxcTRnoj0=/300x300/triforce.png`), even when in the `main` branch 😢

**Comment by tschaffter** [comment]
Let's try again when the PR #1471 is ready for review.

**Comment by tschaffter** [comment]
@vpchung The PR that updated the image service has been merged after Maria confirmed that she can see the organization logo in the app. Could you please try again after updating your `main` branch?

**Comment by vpchung** [comment]
Okay, it most definitely might just be me who is having issues then:

![Screen Shot 2023-05-03 at 10 57 51 AM](https://user-images.githubusercontent.com/9377970/236003850-a41d4d70-fb56-4c0c-bf34-ea340443f0b2.png)

**Comment by tschaffter** [comment]
Thomas and Verena to meet to fix the remaining issues.

**Comment by tschaffter** [comment]
Added to Sprint 23.05

**Comment by tschaffter** [comment]
@vpchung Let's met to troubleshoot the issue together.

**Comment by vpchung** [comment]
Issue has been resolved (there was an issue with my workspace)
