### ISSUE TITLE
[Story] Improve the challenge and organization profile pages

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1474]
### What projects is this story for?

OpenChallenges

### As a user, I want

To improve the look and feel of the overall app, including the profile pages

## Must have

- [x] Add more images to the homepage
- [x] Remove user-related functionality from the navbar
    - [x] Log In
    - [x] User dropdown
- [x] Add padding around the challenge profile page
- [x] Re-align the text in the challenge profile page's breadcrumbs
- [x] Remove "Topics" section from the challenge profile page
- [x] Merge "Challenge Details" tab into the "Overview" page
- [x] Remove "Edit Profile" text from organization profile page
    - [x] In the mockup, we currently use "Request to Join" for non-members, but since we are not implementing a user system yet, I will use "Go to Website" instead (it will be redundant with the link in the profile) 

## Should have

- [x] Remove timeline bar from the challenge profile page (too many use cases to account for, i.e. not all challenges have defined start/end dates, etc.; does not add enough value to justify amount of effort to debug current issues)
    - [x] Add start and end dates to the top section of the challenge profile page

## Could have

- [ ] Remove the paginator for 0 results (either that or "sticky" it to the bottom)
- [x] Replace all current image assets with images from Thumbor
- [x] Increase the search bar on the home page 
    - [x] Maybe move into a new section altogether? See [mockup](https://www.figma.com/file/yAeIrg6Whc8Bqj2EnG4MWP/OpenChallenges?node-id=1485-3789&t=RkWEP3YrdXIkX1pJ-0) for reference.

## Won't have (this time)

- [ ] In the Goals section, maybe do a table instead of cards?

### Acceptance criteria

- All Must-Haves should be implemented

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
@vpchung Since you started the implementation I thought we could use this ticket to track the work. Can you please update the body of this story with the required information? Do you have an approximate timeline for the completion of this story?

**Comment by vpchung** [comment]
Thanks, @tschaffter - I added the MSCW checklist I was following above.  Please feel free to add any additional suggestions, CC @mdsage1
