### ISSUE TITLE
[Story] Enable external data contributors to add and curate OC data

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1486]
### What projects is this story for?

OpenChallenges

### As a user, I want

As an external data curator, I want to be able to submit requests to add/update OC data so that the challenges/organizations I'm aware of are accurately represented in OC.

### Description

The goal of this story is to design and implement a solution to enable external data contributors to contribute to the OC data, e.g.:

- Submit new challenges or organizations
- Update the data of existing challenges and organizations

## Specifications:

- Submitting data should be as easy as possible for data curators without requiring them to read extensive docs or know how to code.
- The data contributors should not be able to modify the ground source by themselves: an OC developer should be able to review the submitted changes before accepting them.
- Other specification?

## Notes

- Flyway enables us to define incremental changes to the table structures and data. Maybe this feature could be handy to keep track of how we evolve the data models and for repeating data update (e.g. the data update apply on Week X could be captured in its own SQL file)?

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
We are going to create a new Google sheet that allows stakeholders to update the data. Then Verena would merge this new spreadsheet to the main one.

**Comment by tschaffter** [comment]
@vpchung Here are notes from our last conversation:

- We are inviting 3-5 organizations to access the preview and update their data during the private preview.
- Members from an org should be able to suggest new challenges, update existing challenges and update org details.
- Members from an org should not be able to overwrite the suggestions made by members from another orgs.
- We should know the identity of who is making a suggestion (mainly for provenance).

**Comment by tschaffter** [comment]
@vpchung I think that the solution you came up with satisfies our current needs, that is, to enable external data contributor to contribute data to the OC DB. Is that right?

**Comment by vpchung** [comment]
@tschaffter yes, via [this Google sheet](https://docs.google.com/spreadsheets/d/1-3LO7h_JJf6rnEBvVJWjDD4FBmHCu-oiBNlxvSSnkwo/edit?usp=sharing).

Once we identify the 3-5 organizations for the private preview, I will update it so that it contains one sheet per organization where editing rights will be limited to their list of challenges.  That way, we can have some control over who can edit what on the OC DB.
