### ISSUE TITLE
[Bug] Avatar is not displayed on organization profile

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#1501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What projects are you seeing the problem on?

OpenChallenges

### Current behavior

The organization profile page does not currently display the organization logo as its avatar, e.g.

![Screen Shot 2023-05-04 at 12 02 25 PM](https://user-images.githubusercontent.com/9377970/236303549-37603d8a-8fba-4420-8b8b-32beb5f25dbb.png)

I also checked with the organization card and the logo does display there okay:

![Screen Shot 2023-05-04 at 12 02 18 PM](https://user-images.githubusercontent.com/9377970/236303675-2324fda2-d9ca-4b09-a598-ad629bbed578.png)

### Expected behavior

If the org has a logo, it would be ideal to display it on the organization profile. Something like this:

![Screen Shot 2023-05-04 at 12 07 51 PM](https://user-images.githubusercontent.com/9377970/236304674-ed4cb4c8-598e-4034-81bf-fd32d3a71a00.png)

### Anything else?

I did attempt to debug on my own first, but I couldn't quite figure it out.  The code used to get the avatar URL seems to be the same between the `organization-card` component (where the logo does correctly display) and `org-profile` component (where the logo does not display). I'm thinking maybe the issue is due to Observable? Or maybe the subscribe event?

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vpchung** [comment]
Not sure if this will help at all, but I get a 404 in the console log regarding the logo:

![Screen Shot 2023-05-04 at 12 24 16 PM](https://user-images.githubusercontent.com/9377970/236309052-ec61840a-ba39-49dd-bec2-f62f0ee7a891.png)

**Comment by tschaffter** [comment]
I'm working on it!

**Comment by tschaffter** [comment]
The bug happens because the organization service builds the avatar URL when getting a list of organizations, not yet when a single org is requested.
