### ISSUE TITLE
[Bug] Challenge search page does not reset

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#1505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What projects are you seeing the problem on?

OpenChallenges

### Current behavior

The results page does not reset after clearing the search bar:

https://user-images.githubusercontent.com/9377970/236341340-bdf0f6c0-ed01-4fa6-ae9e-7f77da5045e8.mov

This behavior is not seen with the Organizations Search page.

### Expected behavior

I expect the Challenges Search page to behave like the Organization Search page, in which clearing the search bar will display all of the results again.

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vpchung** [comment]
I did some more sleuthing and I think the issue may be related to the query parameters in the URL.  When the search term gets removed from the search bar, the url becomes `http://localhost:4200/challenge?searchTerms=` but the page doesn't reload for it:

![Screen Shot 2023-06-02 at 10 08 44 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/6bb79124-a6e6-41bf-a2ee-8da29f9ca3fb)

If I were to refresh the page or go to http://localhost:4200/challenge?searchTerms= directly, then the page behaves as expected:

![Screen Shot 2023-06-02 at 10 08 01 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/ea595f5f-0e61-4dad-8036-e0a234800b56)

**Comment by tschaffter** [comment]
Thanks @vpchung ! I'm meeting with @rrchai in a few minutes and I'm hoping this is an issue he can have a look at.

Filters that have empty values shouldn't be included in the URL to keep the URL shorter. Instead of `http://localhost:4200/challenge?searchTerms=`, we should have `http://localhost:4200/challenge`.

**Comment by tschaffter** [comment]
Added to Sprint 22.06.

**Comment by vpchung** [comment]
Sounds good, thank you!! @rrchai -- let me know if you'd like to me to try to take a stab at it too.
