### ISSUE TITLE
[Feature] Display 3 or more challenge results per row on MBP 13 inches

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1527]
### What projects is this feature for?

OpenChallenges

### Description

On a MBP 13 inches (2560 x 1600, Firefox), the challenge search page shows two results per row. It would be more convenient to show three cards at least on this relatively common type of display so that to add more information on the screen at once and reduce scrolling.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
@vpchung How many SP would you assign to this ticket?

**Comment by vpchung** [comment]
1 point - working on it now!

**Comment by vpchung** [comment]
@tschaffter can you share what it looks like on your end?  On my MBP 13", I see 3 cards per row:

<img width="1680" alt="Screen Shot 2023-05-10 at 2 05 02 PM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/4d946b91-a5e0-4e68-9172-01463c95b1b7">

Unless you meant to show more than 3 cards?

**Comment by tschaffter** [comment]
I actually shared an incorrect screen resolution and not the one currently applied. My current screen resolution is 1440x900.

Here is what I see:

<img width="1436" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/6dac9cd2-35e5-4534-840f-35e8a7c272a1">

<img width="827" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/b3a3d321-2a5d-476a-9213-54a5dca80be2">

**Comment by vpchung** [comment]
Perfect - that helps!
