### ISSUE TITLE
[Bug] Paginator not working as expected on org profile page

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#1530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What projects are you seeing the problem on?

OpenChallenges

### Current behavior

In the Challenges tab of an organization profile page, _all_ challenge cards are displayed rather than the default 12.  If we were to adjust the number of results returned, then the correct number of cards will display:

https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/10d7eb62-774c-4e48-a7e2-f8a09528bd88

### Expected behavior

By default, the paginator selects "12" as the number of cards to display, so I would expect only 12 cards should be shown, not all of them.

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
@vpchung Didn't the default page size use to be different (20, 50 and maybe one more)? I have to admit that it kind of bugged me to reach the bottom and see a partial row of results. But if the number of results displayed per row is variable, multiple or 12 (or actually 3) would not be suitable.

**Comment by tschaffter** [comment]
Is the blue for the menu item darker than the blue of the navbar, or am I this an optical illusion?

**Comment by vpchung** [comment]
> Didn't the default page size use to be different (20, 50 and maybe one more)?

i don't think I was present for this conversation for using [20, 50, 100].  I recall suggesting showing items in multiples of 12 instead, since that was the common product between 2, 3, and 4 (which coincide with the number of cards per row depending on screen size).  I'm guessing this 12 is the legacy code from that.

Is there a reason why you don't think 12 is suitable?

**Comment by vpchung** [comment]
> Is the blue for the menu item darker than the blue of the navbar

It's the darker blue used in the footer.

**Comment by vpchung** [comment]
## Update

I was not able to figure out the issue from the frontend side, so I will be unassigning myself for now.

**Comment by vpchung** [comment]
Ahh, okay, that makes a lot of sense. Return to Backlog?

**Comment by tschaffter** [comment]
@rrchai Actually there is probably an issue with the paginator because independently of the filters applied, the page should not show more than N challenges where N is defined by the paginator.

**Comment by rrchai** [comment]
The avatars of orgs in dropdown are retrieved using imageService. I borrow @tschaffter code used in org-search page. I notice there are a little bit delay (2-3s) to get all orgs. For example, when the challenge-search page is loaded, users will not see options in the organization dropdown until the orgs including avatars are all queried in 2-3s.
It's not a big deal now, but may cause longer delays with more orgs added into the database in the future.

**Comment by rrchai** [comment]
I can reproduce the error - looking into it soon.
