### ISSUE TITLE
[Feature] Replace mock supporting organizations on the challenge profile page

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1537]
### What projects is this feature for?

OpenChallenges

### Description

As a prospective participant, I want to know who are supporting the organization of a challenge so that I have more information to decide on whether I want to participate to a given challenge.

As a prospective challenge organizer, I want to know what organization supported Challenge X so that I can contact them for the challenge I organize.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
@vpchung pointed out that we don't currently don't have a way to filter challenges by organization (work in progress, #1403 ) and to get the orgs that contributes to a challenges. I'm marking this ticket as Blocked for now.

**Comment by tschaffter** [comment]
Added to Sprint 23.06

**Comment by tschaffter** [comment]
@rrchai This task is no longer blocked since we can now filter challenges by org.

**Comment by vpchung** [comment]
@rrchai @tschaffter jumping into the convo here :-)

We already have a table in both the challenge and organization services that has this information available:

![Screen Shot 2023-06-13 at 2 11 04 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/91554fed-cf6b-4bbc-875d-6a91c731d26d)

I believe the APIs just have to expose this now.

**Comment by tschaffter** [comment]
@rrchai @vpchung That's right, we have the data and the challenge service partially supports this feature with the existing Java class `ChallengeContributionEntity` that links supporting organization to challenges.

The next steps are to define how we want to expose these data in the API description. One option is to add a property to the `Challenge` object that includes an array of contributors (org id, role). Another option is to provide this information via a dedicated endpoint, e.g. `challenges/{challengeId}/contributors`.

Option 1 comes the cost of extra backend processing to get challenges (even when contributors data is not needed, e.g. on the search page) and more data to transfer. For the sake of simplicity and performance, I propose to go with the second option. The API client will provide a dedicated method that we can call when needed.

@rrchai @vpchung Does one of you want to give a try adding this new endpoint to the API description?

**Comment by vpchung** [comment]
A dedicated endpoint makes much more sense, imo - thanks!

I most likely won't have time to work on this until near the end of the sprint.  @rrchai , what about you?

**Comment by rrchai** [comment]
@tschaffter @vpchung I can give a try to add the endpoint this sprint.

**Comment by tschaffter** [comment]
This ticket depends on #1666, which is planned for next sprint. So I'm also moving this ticket to next sprint. The priority goes to implementing the page state in the URL this sprint.

**Comment by rrchai** [comment]
@tschaffter While I have been already working to update the front-end, I realize the orgs(contributions) can not be retrieved by current `ChallengeContributionService` and `OrganizationService` - see "Blocked" in #1668.

Moving to next sprint sounds good to me. Thanks.

**Comment by tschaffter** [comment]
@rrchai I will review the API description and backend as I may have forgotten to rename something. I will also update the app so that it will work with the latest client, then merge to `main`. That way the backend will be ready when we start working on the frontend next sprint.

**Comment by tschaffter** [comment]
This ticket is no longer blocked since the completion of #1669.

**Comment by tschaffter** [comment]
Blocked by #1666, which will define the UI/UX for displaying the orgs that contributed to a challenge.

**Comment by rrchai** [comment]
I will work on this today.

**Comment by rrchai** [comment]
@tschaffter I think I confused you about the backend support I needed for this ticket. 

In order to get the challenge contributors (orgs) in the Challenge Profile page, we could use either of way listed below:
1. Make organizations (`orgId`) property accessible in the Challenge object -> Get all contributors of the challenge using all `orgIds`
2. Add `challenges` to `OrganizationSearchQuery` ->  Get all contributors of the challenge by query using `challengeId`

Adding "query Org object by login` will support the first approach, but still need to get "organizations" property in Challenge object. 

I think the second approach is more straightforward to me, thus I created the associated ticket:
  - #1874 

Do you think we could move this ticket to next sprint and I am more than happy to support ^ backend feature.

**Comment by tschaffter** [comment]
@rrchai We can get the list of orgs that contributed to a challenge with the endpoint `/challenges/{id}/contributions`, which we added recently.

```console
https://dev.openchallenges.io/api/v1/challenges/1/contributions
```

```json
{
  "number": 0,
  "size": 2,
  "totalElements": 2,
  "totalPages": 1,
  "hasNext": false,
  "hasPrevious": false,
  "challengeContributions": [
    {
      "challengeId": 1,
      "organizationId": 75,
      "role": "sponsor"
    },
    {
      "challengeId": 1,
      "organizationId": 1,
      "role": "sponsor"
    }
  ]
}
```

**Comment by tschaffter** [comment]
> Do you think we could move this ticket to next sprint

Absolutely!

**Comment by tschaffter** [comment]
Moving to Sprint 23.08

**Comment by rrchai** [comment]
> We can get the list of orgs that contributed to a challenge with the endpoint /challenges/{id}/contributions

Oh right. I totally missed the endpoint. Thanks for reminding.
