### ISSUE TITLE
[Feature] Add favicon to the OC app

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1569]
### What projects is this feature for?

OpenChallenges

### Description

Set the OC logo as favicon so that the logo appears in the browser tabs, bookmarks, etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
@vpchung Thanks for taking the first pass on this feature request. Here are a couple of pointers:

- [Google: Define a favicon to show in search results ](https://developers.google.com/search/docs/appearance/favicon-in-search)
- See how to [convert SVG image to ICO with ImageMagick](https://gist.github.com/azam/3b6995a29b9f079282f3)
  - Installing ImageMagick on Debian: `sudo apt update && sudo install imagemagick`

**Comment by tschaffter** [comment]
Added to Sprint 23.06

**Comment by vpchung** [comment]
> [Google: Define a favicon to show in search results](https://developers.google.com/search/docs/appearance/favicon-in-search)

Thanks for sharing the pointers, @tschaffter .  I initially uploaded a 32x32 favicon but have since updated it to 48x48, so that it aligns with Google's guidelines.
