### ISSUE TITLE
Remove '2024' for now?

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#1594]
Nit: the app currently shows 2024 as a facet option. Seeing that we're still in the first half of 2023, I propose removing this option (for now).

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/491e29f4-4ece-49f9-9fb8-cc4ed1246e07)

**Comment by tschaffter** [comment]
We currently don't have upcoming challenges in 2024 in the data (SQL). I'm OK with removing 2024 for now so that we don't display an empty page.

**Comment by tschaffter** [comment]
The year options displayed are parametrized based on the current year. It would be interesting to update this "algorithm" to take into account the year of the oldest and newest (i.e. last challenge to start) challenges. We could then fetch from the challenge service the year of the oldest/newest challenge years (another PR).

**Comment by tschaffter** [comment]
Added to Sprint 23.06

**Comment by tschaffter** [comment]
Done
