### ISSUE TITLE
[Story] Identify what an R app and R library are

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1619]
### As a user, I want

NA

### Description

This monorepo has two types of projects:

- app (`apps/`)
- library (`libs/`)

Each project (app or lib) defines a set of tasks that it implements in its `project.json`. Examples are `build`, `test`, `lint` or any other task required by the project.

The goal of this ticket is to identify what technologies are required to develop R apps and libraries in this monorepo. For example, the dependencies of a Python project are managed with Poetry. The version of Python needed by a given project is managed with Pyenv. The only type of Python app currently in the monorepo is a REST API. Another type of Python app that could be added in the future is CLI. This monorepo has both REST API and CLI examples for TypeScript.
  - A Python app example is [apps/schematic/api](https://github.com/Sage-Bionetworks/sage-monorepo/tree/main/apps/schematic/api)
  - A Python library example is [libs/schematic/api-client-python](https://github.com/Sage-Bionetworks/sage-monorepo/tree/main/libs/schematic/api-client-python)

@andrewelamb @afwillia @jaeddy What do you think an R app and library should be in the monorepo? There are possibly multiple answers for what an app is (e.g. REST API and CLI). What tools should be used to manage the dependencies of an R project? Using Pyenv as a reference for managing different version of Python, is there a similar tool to manage multiple versions of R?

### Acceptance criteria

- @andrewelamb, @afwillia and @jaeddy signed off on the framework and tools the monorepo should support to develop R apps and libraries

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by andrewelamb** [comment]
@tschaffter I can add some more to this later, but [renv](https://github.com/rstudio/renv) does a lot of the same things poetry does, and could be considered equivalent.

**Comment by jaeddy** [comment]
(copied from Slack)

> i haven’t done serious R development in a while, so i can’t guarantee that these resources are the latest and greatest… but might be a good starting point. the #r channel would also be a good place to ask and/or cross-check the resources below

- **R package development**
  - the [R Packages](https://r-pkgs.org/) book describes best practices, and includes info about some core packages (e.g., devtools, testthat, etc.)
  - i’m not sure how much there is in terms of “frameworks” for building R libraries; there are a view different paradigms for object oriented programming, which are described in the [Advanced R](https://adv-r.hadley.nz/oo.html) book
  - one could potentially view [Bioconductor](https://contributions.bioconductor.org/) as a pseudo-framework (i.e., specific and opinionated ways to build packages), but that will probably be less relevant to most of our R tools
- **Shiny app development**
  - similarly, there are a couple books describing best practices for app development: (1) [Engineering Production-Grade Shiny Apps](https://engineering-shiny.org/index.html) - published “independently” a few years ago; and (2) [Mastering Shiny](https://mastering-shiny.org/) - written and published by Hadley Wickham / Posit, so maybe more authoritative, but not sure if it includes as much about production deployment
  - the first book references golem (see [golemverse](https://golemverse.org/)), which is a framework for building Shiny apps, and is somewhat unique in that it treats Shiny apps as R packages
  - another more recent framework is [Rhino](https://appsilon.github.io/rhino/), developed by  [Appsilon](https://appsilon.com/) — i think it doesn’t require your app to be an R package, but might be more compatible with other web dev frameworks (see screenshot below)
  - Appsilon also has a lot of other great resources for building “enterprise grade” Shiny apps, including a nice [blog](https://appsilon.com/blog/)
- **multiple versions of R**
  - i’m not sure if this is something supported by renv (see [package site](https://rstudio.github.io/renv/articles/renv.html)), but might be worth checking
  - here’s a [blog post](https://jacobrprice.github.io/2019/09/19/Installing-multiple-parallel-R-versions.html) from someone describing their approach for installing/managing multiple R versions on Mac OSX — it might be more straightforward in Linux environments

![image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/5033229/29ed283c-0b89-4b08-9906-08aa6c4393ed)

**Comment by tschaffter** [comment]
The articles describe how to manage multiple R versions on the same host:
- [Installing multiple parallel versions of R on Mac and getting back up and running quickly by simplifying package installation](https://jacobrprice.github.io/2019/09/19/Installing-multiple-parallel-R-versions.html)
- [Managing Multiple R Installations on Linux](https://jeff.vtkellers.com/posts/data-science/managing-multiple-r-installations-on-linux/)

**Comment by tschaffter** [comment]
Initially a single version of R should suffice. I will try these [instructions](https://docs.posit.co/resources/install-r/#specify-r-version) from Posix to install R with a pinned version.
