### ISSUE TITLE
[Task] Use the color version of the OC logo in the nav bar

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1639]
### What projects is this story for?

OpenChallenges

### Description

We are currently using the white version of the logo. Instead we should use the color version.

<img width="600" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/08bee4d0-e78a-4d36-aa1e-bf0a396cee48">

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by vpchung** [comment]
Is this up for discussion by any chance? I'm not a fan of the colored icon against the blue navbar:

![Screen Shot 2023-06-13 at 11 04 28 AM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/b6589d6d-b858-4c1a-8ab7-c1b1068deb6d)

White stands out better imo.

**Comment by tschaffter** [comment]
@vpchung It's a tough call. Shall we poll the slack channel?
