### ISSUE TITLE
[Bug] Unable to refresh Org Profile page

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/sage-monorepo#1642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What projects are you seeing the problem on?

OpenChallenges

### Current behavior

After refreshing a Org Profile Page, the page will become blank page with below error in the console:

<img width="507" alt="Screen Shot 2023-06-12 at 10 05 57 PM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/73901500/8c23dc88-efd0-49d9-853c-5ce83bba3270">

Only if going back home page (`localhost:4200`) and then going to the Org Profile page will be able to re-access the page. 

### Expected behavior

Refreshing a Org Profile page without problems.

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
- Does this error occurs on other pages that are not `/`?
- Does this error occurs when running the app with its dev server and/or container?

This old [post](https://stackoverflow.com/questions/35284988/angular-2-404-error-occur-when-i-refresh-through-the-browser) with recent comments may help.

**Comment by tschaffter** [comment]
@rrchai I'm taking a shot at this issue as it may solve another issue I just bumbed in.

**Comment by tschaffter** [comment]
> Does this error occurs on other pages that are not /?

Several pages can be reloaded properly but not the following pages:

- Org profile page
- Challenge profile page

> Does this error occurs when running the app with its dev server and/or container?

The error occurs when running the app with its dev server and container, so it's likely an issue with the app itself and not Nginx.

For example, the URL `http://localhost:4200/challenge/2` should redirect to `http://localhost:4200/challenge/2/breast-cancer-prognosis` but this redirection no longer works because the app fails to loads resources like `vendor.js`.

**Comment by tschaffter** [comment]
The issue seems to occurs when we access a sub sub page, e.g.

- `http://localhost:4200/about` is fine
- `http://localhost:4200/about/hello`: expected to be 404 because it doesn't exist, actual: the same error as reported in this ticket.

**Comment by tschaffter** [comment]
Adding back <base href="/" />  to the index.html of the app solves the issue. This line has been removed recently in this [PR](https://github.com/Sage-Bionetworks/sage-monorepo/pull/1596/files).
