### ISSUE TITLE
[Bug] Org cards are not shown if the request to the get the image URL fails

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What projects are you seeing the problem on?

OpenChallenges

### Current behavior

The org cards are not shown on the org search page when their requests to get their logo URL - not the logo itself - fails. I bumped into this case when working on routing the requests to Thumbor via the Apex.

![image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/aa3ed735-55ab-4549-b99b-db70b35a743c)

### Expected behavior

An org card should still show if the request to get its logo URL fails. In this case, we should show the initial avatar as backend.

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
This bug may be because of an issue I have in the PR #1650. I'll update this ticket once this PR is complete.

**Comment by tschaffter** [comment]
This behavior was observed on the home page (featured orgs) as well as on the org search page.

**Comment by tschaffter** [comment]
Moved to Sprint 23.07

**Comment by rrchai** [comment]
I can reproduce the error if image service is stopped.
