### ISSUE TITLE
[Story] Identify how to show the contributing orgs on the challenge profile page

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1666]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a prospective participant, I want to know what organizations are contributing to a challenge so that I can better identify whether I want to participate to this challenge.

### Description

The OC data model captures the contributions made by organizations to a given challenge as well as the role they took. The goal of this story is to review the current UI design before we start implementing it.

The current UI design has the menu item "Sponsors" on the challenge profile page (see [Figma](https://www.figma.com/file/yAeIrg6Whc8Bqj2EnG4MWP/OpenChallenges?type=design&node-id=0-1&t=0mOit5ByDcKuaLtl-0)). 

<img width="816" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/4006ffcb-77e6-4568-99fc-68552f99143e">

Previously, a "sponsor" was meant to describe any org that contribute to a challenge. Since then, the "sponsor" object has been replaced by the "contribution" object. A contribution includes currently three pieces of information: a challenge ID, an org ID and the role taken by this org. Examples of roles are `challenge_organizer`, `data_contributor`, `sponsor`.

Proposal:

- Rename the section "Sponsors" to "Organizations" and show all the orgs
  - Instead of creating a new org card that shows the type of contribution (one org may take more than one role), we could group orgs by type of contributions
  - An initial version could be to simply show all the orgs under the section "Organizations". Grouping the orgs by contribution type could be done in a second release/iteration.

@vpchung What approach should we take?

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Added to Sprint 23.07

**Comment by tschaffter** [comment]
The ticket #1537 depends on this ticket.

**Comment by vpchung** [comment]
@tschaffter@rrchai perhaps we can start with a simple change such as this?

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/1890ff4c-019b-410f-a97d-e2a3bd4c29aa)

Then, pending feedback, we can further organize into categories by reusing the tab feature we implemented in the challenge profile pages:

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/0df00c3d-464c-4820-9cd5-bbfdb6620754)

**Comment by vpchung** [comment]
[See Figma mock up here](https://www.figma.com/file/yAeIrg6Whc8Bqj2EnG4MWP/OpenChallenges?type=design&node-id=52-1414&mode=design&t=cq5hXFQdBYrx60bm-0)

**Comment by tschaffter** [comment]
Looks good! I added one comment to Figma.

**Comment by vpchung** [comment]
@rrchai for simplicity's sake, let's go with the first (top) design!
