### ISSUE TITLE
Reduce the size of challenge "long" description

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#167]
## Background

There are two places where a description of a challenge can be specified:

- `Challenge.description`: this one is mean to be short so that queries on Challenges are not slowed down. Short enough to be suitable for cards.
- `ChallengeReadme`: meant to store extended description of the challenge, possibly including images and in markdown format in the future.

## Proposal

@vpchung proposed to remove the option for challenge organizers to provide an extended description of the challenge (README). The motivation is that such description would be available on the challenge platform used to organize the challenge.

Pros:
- Remove duplicated challenge description that is already available on the challenge platform
- Reduce information that challenge organizers need to specify in the challenge registry
- Further standardize the content of challenge pages

Cons:
- Less information about the challenges "archived" in the challenge registry

**Comment by tschaffter** [comment]
## Option 1

- Replace `ChallengeReadme` by `Challenge.summary` (max length N chars)
- Keep `Challenge.description` with max length 280 chars and use it in challenge cards

## Option 2

- Remove `ChallengeReadme` and effectively replace it by the existing `Challenge.description` (max length 280 chars)
- Add `Challenge.headline` (max length M chars, e.g. 80 chars)

@vpchung Which of the above options - or variants of these options - do you recommend? Which of the two properties would you use on the challenge card?

**Comment by vpchung** [comment]
Option 2 sounds more self-explanatory to me!  I fear that with option 1, a new user wouldn't know the difference between `summary` and `description` without referring to our docs first (which I guess isn't bad, but I would prefer the attribute names to be as obvious as possible).
