### ISSUE TITLE
[Story] Make the footer sticky again

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1687]
### What projects is this story for?

OpenChallenges

### As a user, I want

NA

### Description

The content of a few pages is briefly empty during their loading, which leads the footer to appear just below the navbar. This behavior creates a flash that original from the light-grey background color of content section and the dark blue of the footer, then back to light-grey. This flash may impair the navigation comfort of the user.

This flash appears when navigating from the challenge search page to a challenge profile page, from the org search page to the org profile page, but not from the home page to the challenge search page. See the example shown below.

On the org search page:

<img width="944" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/f7627051-2467-453c-a47a-37e881225e0b">

After clicking on an org card, the org profile page starts to load. For a moment, the content is empty and the footer appears just below the navbar.

<img width="943" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/fcf0d676-4fe3-42c0-99ab-7f2cc11feb5e">

The page content is displayed and the footer is pushed back to the bottom of the page.

<img width="941" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/97c0d433-e76b-4454-a493-3d75ab75c6f1">

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Added to Sprint 23.07

**Comment by tschaffter** [comment]
@vpchung Do you know why this flash is occurring on the search pages but not on other pages?

**Comment by vpchung** [comment]
I do not.  My initial thoughts would be that the data is being queried and loaded?  Whereas with the home and search pages, there are areas where the data is static.

**Comment by tschaffter** [comment]
@rrchai Since you made the footer sticky (#1323), could you please have a look at why the footer is no longer sticky on the challenge and org pages?

**Comment by tschaffter** [comment]
Or more likely it's no longer sticky on any page. As Verena pointed out, the other pages have static content that is displayed instantly, effectively preventing the footer to appear near the navbar.

**Comment by rrchai** [comment]
I can reproduce the behavior when I set organization$ to `undefined`, aka no org data is loaded in Org Profile page. I will look into it. Thanks for reporting,
