### ISSUE TITLE
[Story] Capturing `createdAt` and `updatedAt` values in OC Data

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1691]
### What projects is this story for?

OpenChallenges

### Description

This ticket was suggested by @vpchung . The idea is to capture the values of `createdAt` and `updatedAt` properties in the OC Data and to include them to the SQL data dumps.

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Added to Backlog

**Comment by tschaffter** [comment]
@vpchung The values must actually follow the [DATETIME](https://mariadb.com/kb/en/datetime/) format specified by MariaDB, not the format specified by OC API description, when dumping these values to SQL files.

**Comment by vpchung** [comment]
@tschaffter oh, great! I'm glad I can use "pretty" text to specify the datetime, e.g. `("2012-04-19 13:08:22")`
