### ISSUE TITLE
[Feature] Individually select the orgs to feature on the home page / search page

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1694]
### What projects is this feature for?

OpenChallenges

### Description

The home page currently shows four organizations that we feature, which are the four orgs with the largest number of challenges organized (fetch using the challenge count sorter). Arguably, the largest orgs should not be the one we should further advertise.

The feature proposed consist in adding a flag `Organization.featured` to the data model and enable to query them via the API. That way, we can manually select in the OpenChallenges Data which org should be featured.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
We used to have a filter - or sorter - for featured orgs but there is no trace of it in the org search page.

**Comment by rrchai** [comment]
AC:
- #1766 
- #1767 
- #1768
