### ISSUE TITLE
[Story] Identify framework to build the docs of Sage Monorepo

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1735]
### As a user, I want

As a Developer, I want the documentation of this monorepo to be visible and accessible so that I can quickly locate the information I need.

### Description

The documentation of this monorepo is mainly located in the `docs` folder. The docs is written in Markdown, which is a syntax accessible to many developers. Visualizing this docs with GitHub or VS Code preview is OK, but we could make the doc more visible by publishing it to GitHub Pages. Moreover, adopting a framework like [mkdocs-material](https://squidfunk.github.io/mkdocs-material/) would provide additional features such as quick access to different versions of the docs and access to a search bar.

The goal of this ticket is to identify the framework that we will use to generate the documentation page of the monorepo.

### Acceptance criteria

- The framework is compatible with Markdown files
- The framework provides a search bar

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
[Trivy docs](https://github.com/aquasecurity/trivy/tree/main/docs) is built with [mkdocs-material](https://squidfunk.github.io/mkdocs-material/).

**Comment by tschaffter** [comment]
I stumbled upon [GitBook](https://www.gitbook.com/?utm_source=content&utm_medium=trademark&utm_campaign=-LGsE7zdvzHI5cG-XV6p-2022730153) today (see this [example](https://semantic-release.gitbook.io/semantic-release/v/beta/)).

**Comment by vpchung** [comment]
After doing a quick comparison with Bard:

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/9a39b219-5eb4-4eaf-bddf-cf502c492e9c)

I will move forward with mkdocs for now :slightly_smiling_face:
