### ISSUE TITLE
[Enhancement] Use action words in OC description

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#1827]
## Sage Design feedback

Current description on home page:

> OpenChallenges strives to provide a centralized hub of biomedical challenges from various hosting organizations. Our goal is to empower both participants with the most up-to-date information about relevant challenges, as well as organizers with standardized challenge templates and intelligence.

Does this mean OpenChallenges is still working towards this goal or has it already been accomplished?

Maybe instead of "strives" and "our goal", say something more TA-DAH! WE DID IT. e.g.

"OpenChallenges provides a centralized hub... We empower both participants..."

**Comment by tschaffter** [comment]
I agree with this suggestion. As the first thing that users would read, I would make this paragraph shorter and use simpler/more impactful words.

Here is a modified version of it that I used in the email sent to Team Sage.

> OpenChallenges aims to be a centralized hub for biomedical challenges and more. It provides participants with the most up-to-date information about relevant challenges, and organizers with standardized challenge event templates and intelligence.
