### ISSUE TITLE
[Enhancement] Add captions under logos on home page

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#1829]
## Sage Design feedback

Current list of logos (sponsors?):

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/9db47e05-190a-4869-b4dc-151d2ccb6fc3)

It is currently not stated any where who/what these logos represent, and so, it assumes that users are familiar with AWS and/or Sage (which may not always be the case).  It may be a good idea to also include a caption or title of the organization/sponsor name.

**Comment by tschaffter** [comment]
I agree with this suggestion. Here are changes I'd like to propose:

- Remove AWS logo as we probably aren't authorized to use it
- (Optional) remove the blue border around the ITCR logo
- Use Sage logo with its name as the logo/icon is not known enough to recognize the org

**Comment by rrchai** [comment]
We could choose the logo with their name on it - hopefully most of the sponsors have the version with name.

**Comment by tschaffter** [comment]
Here is an example of a list of logos that is more accessible:

<img width="1440" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/7e9fd7fa-54ae-4bc8-9e68-fb00b839a4da">

**Comment by vpchung** [comment]
An alternative logo for ITCR could be the one currently on the [NIH-ITCR website](https://itcr.cancer.gov/).  Our "sponsors" list would then look something like this:


![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/8bf0ea45-2dab-42c9-92c0-5582a02de49b)

**Comment by tschaffter** [comment]
@vpchung The alternative logo looks better. Let's go ahead with it. I could try to upscale and remove the background of the ITCR logo with Illustrator in the future.
