### ISSUE TITLE
[Enhancement] Remove drop shadows from non-interactive cards

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#1830]
## Sage Design feedback

Interactive cards:

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/497b24bf-21a4-4903-b5b8-8835305529c6)

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/9c04cebc-eece-4f69-9ac7-0c6cddda731d)

Non-interactive cards:

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/d54e2c9c-71ac-4bbd-acc7-b129b2b59578)

There is no distinction between an interactive vs. non-interactive cards, e.g. there is a drop-shadow with both designs, which could confuse users and/or make them think there is a bug with the goal-cards.

**Comment by tschaffter** [comment]
One suggestion from Adam was to avoid having a shadow (avatar) on top of another shadow (card). I agree with this. This can be solved by removing the shadow of the avatar (when displayed inside the card). Without the shadow, we may then need an thin outline to separate the content of the avatar from the rest of the card (especially if the background of the avatar is the same color as the card).

There is actually a difference between the interactive and non-interactive card, which is the cursor of the mouse.

Another option could be to slightly change the background color of the card below the cursor. If we don't use a shadow around the card, we could add an invisible border around the challenge card and change the color of this border when the cursor is over the card.

**Comment by rrchai** [comment]
I suggest removing the box-shadow or using a light shadow for non-interactive cards seem. Besides, adding clear borders if it's a card. The clear box-shadow on a box/card will make me spontaneously think it's clickable.

**Comment by vpchung** [comment]
> The clear box-shadow on a box/card will make me spontaneously think it's clickable.

Same; I think removing the drop shadow from goal-cards should be sufficient.
