### ISSUE TITLE
[Enhancement] Provide text for empty fields on Profile pages

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#1834]
## Sage Design feedback

Current profile pages:

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/d84568fa-7ba9-45c5-b53d-c976732552e3)

It may be a good idea to provide some explicit text, e.g. "None provided", rather than leaving fields empty.  That way, it's clear that this information was not found and that it's not a bug with the frontend.

**Comment by tschaffter** [comment]
While discussing with @vpchung today, I suggested that we include an clickable icon next to every values - including empty values - that redirect to a Google form that allows the user to submit a new/different value. Ideally we can include to the URL that redirect to the form an identifier that allows us to uniquely identify the selected key as defined by (resource id, property id) where resource ID could be a challenge id or organization id.

In the Google form, the user would be able to see information about the key (read-only) and a field ideally filled with the existing value (or empty for new value).

OC Data Curators would periodically review the submissions and modify the OC DB in consequence.

**Comment by rrchai** [comment]
I feel adding "None provided" is clear enough for users or even just removing the key without a value. 

> OC Data Curators would periodically review the submissions and modify the OC DB in consequence.

How about sending the request form to owners and let owner decide whether to update the value, while OC should valid the key/value's format backend?

**Comment by vpchung** [comment]
(Since I'm a visual learner) Here's a visual representation of @tschaffter 's proposal:

![Screenshot 2023-07-25 at 12 13 00 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/d10095bf-a0d5-466e-8e7a-ce3314bc0a98)

where clicking on the icon would redirect to a Google Form where some of the values are pre-filled.  For example. say a user noticed a discrepancy with the start date for the "Network Topology and Parameter Inference" challenge, they will then click on the pencil icon next to **Start Date** and be led to this [pre-filled form](https://docs.google.com/forms/d/e/1FAIpQLSdkgAVOuof-tE4PvCnpPbbGnQvvMhLuTkXikDXTbsCHqcMVSw/viewform).

In @tschaffter 's words: _"This approach would have two benefits: 1) better submitter experience and 2) we don’t need to change the Google form if we want to collect values for new attributes."_

I agree this would reduce overhead from the users, but I worry that the design is a little cumbersome?

**Comment by vpchung** [comment]
What about something like this? (rough sketches)

**"Suggest an Edit" in the top section**

![Screenshot 2023-07-25 at 12 32 25 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/914422d7-c43f-4fe8-8513-2aec3a6c5e63)

**"Suggest an Edit" after Challenge Details section**

![Screenshot 2023-07-25 at 12 36 09 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/8ae20566-95f4-4491-9939-dd496759796f)

Clicking on the link would then lead to a [Google form](https://docs.google.com/forms/d/e/1FAIpQLSdkgAVOuof-tE4PvCnpPbbGnQvvMhLuTkXikDXTbsCHqcMVSw/viewform) where only the **Challenge Name** would be pre-filled.  This approach won't be as ready-to-go as the first approach, but maybe this is enough?

**Comment by tschaffter** [comment]
The first design looks like a Hedgehog... A different icon and using a light gray could make it more pleasing to the eye.

That said, I like your last suggestion. The yellow banner is maybe too close to a warning message and points out too much that our data are incomplete. Maybe adopting a still closer to what we use to show when the data have been last edited could fit better. It should be visible but not distracting.

**Comment by vpchung** [comment]
>  It should be visible but not distracting.

Oh, great!  That was my initial thought too, but I thought you would've wanted the suggestion option to be obvious. This was my original idea:

![Screenshot 2023-07-25 at 1 28 20 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/ec57faae-5117-42d9-8da2-e69938da1973)

**Comment by tschaffter** [comment]
My initial thought was that the line was too long and difficult to parse. After thinking about it I think that it's the right level of visibility. It's there but it's not glaring.

**Comment by vpchung** [comment]
Another alternative would be to remove it from the footer and have it as a subtext between the Challenge Details and Organzations sections:

![Screenshot 2023-07-25 at 1 37 57 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/cf60c9d0-c41e-4c82-8ac7-108b50134232)
