### ISSUE TITLE
[Enhancement] Add "See More" to truncated descriptions

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#1835]
## Sage Design feedback

An example long description on profile pages:

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/b2629afa-125c-4302-b252-03c273201f7d)

Where is the rest of the description? As a potential user, it's not clear that the intention of the truncated description is to go to the challenge website to read the rest of the description.

Consider adding some text that says: "(see more on challenge website)"

**Comment by vpchung** [comment]
> Consider adding some text that says: "(see more on challenge website)"

We could also make this a hyperlink?

**Comment by tschaffter** [comment]
@vpchung and I discussed this feature a few month ago so I agree with Adam's comment and Verena's proposed solution "(see more on challenge website)".

**Comment by rrchai** [comment]
> We could also make this a hyperlink?

Hyperlink looks more useful to me than plaintext ~

**Comment by tschaffter** [comment]
@vpchung Is the status of this task In Progress?

**Comment by vpchung** [comment]
### 8/29/2023 update:

This is still a WIP.  Given my current priorities, I did not have time to finish this this sprint.

**Comment by tschaffter** [comment]
Moving to Sprint 23.09
