### ISSUE TITLE
[Enhancement] Revisit "Featured Challenges"

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#1837]
## Sage Design feedback

Current section on Featured Challenges:

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/0b911934-7d55-4ff5-8296-bffca1ea5d7f)

How were these determined? Are these challenges/organizers paying to be featured?

**Comment by tschaffter** [comment]
I agree that we need to rethink what we mean by featured. We have no plan to accept money in exchange of featuring a challenge. I also don't want to arbitrarily feature challenges, e.g. from other organizers we know.

One drawback of the current implementation is that featured challenges must be manually selected/deselected by a member of the OC Team.

One solution to the above pain points could be to allow the owner of an active/upcoming challenge to feature their challenge whenever they want with the following constraints: 1) the challenge can only be featured once, and 2) the challenge is featured for a fixed period of time, e.g. one week. That way challenge owners could boost the visibility of their challenge whenever they want, all challenge owners are treated equally and we don't have to do anything to maintain featured challenges. Here again, we could use a form for challenge owners to let us know when to feature a challenge. Once the data are fully managed in-app, the OC Team wouldn't have to do anything.

> Not sure where to start?

What about showing random challenges? We could also show a random sample of the most viewed and/or least viewed challenges once we have access to analytics data.

**Comment by rrchai** [comment]
> allow the owner of an active/upcoming challenge to feature their challenge whenever they want with the following constraints: 1) the challenge can only be featured once, and 2) the challenge is featured for a fixed period of time, e.g. one week.

Allowing owners of challenge to select featured challenges I think was our goal when we worked for `rocc-app`. The idea with above constraints still sounds good to me. 

1. Display limited number of featured challenges (n <5)
      - From all featured challenges (from all owners), OC could then select what challenges to be displayed first using certain metrics (views #, participants #, prize, etc.).
      - OR Randomly selected from all featured challenges

2. Display a lot of featured challenges (potentially need scrollbar or button to show more, like e-commerce products showcase, see gif)
    - Sort with certain metrics from all featured challenges
 
![Recording 2023-07-25 at 13 52 26](https://github.com/Sage-Bionetworks/sage-monorepo/assets/73901500/a3926da9-e4e3-4a76-99ed-01088571617f)

**Comment by vpchung** [comment]
I'm not a fan of the carousel, so I'm going to x-nay on that..... 🙃
