### ISSUE TITLE
Create Google Forms for external data contributions

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#1845]
Per a discussion with @tschaffter , we are moving forward with collecting data from external contributors through two Google Forms:
* one for adding new challenges
* one for editing existing data on OC

This will replace the previous approach of using [Google Sheets](https://docs.google.com/spreadsheets/d/1-3LO7h_JJf6rnEBvVJWjDD4FBmHCu-oiBNlxvSSnkwo/edit#gid=484902792)

**Comment by tschaffter** [comment]
One requirement is that we can generate a URL to the Google form that include information that uniquely identify the key of the new value submitted (single field data collection form only).

**Comment by vpchung** [comment]
A great suggestion, @tschaffter . 

Following up with our discussion from #1834, here are the three forms we can move forward with:
* [Adding a New Challenge](https://docs.google.com/forms/d/e/1FAIpQLSdLZ6C5ZIzLZS147bmvNm2eJ3kq_88ecHS7ADjD4KaapGhO8g/viewform)
* [Suggest a Challenge Edit](https://docs.google.com/forms/d/e/1FAIpQLSdkgAVOuof-tE4PvCnpPbbGnQvvMhLuTkXikDXTbsCHqcMVSw/viewform?usp=pp_url) (**Challenge Name** will be pre-filled depending on challenge profile)
* [Suggest an Organization Edit](https://docs.google.com/forms/d/e/1FAIpQLSfQbQl11MG_5TXT7fL07YenRD3MIQYfG2lXrpo3jnh_iA4nsw/viewform) (**Organization Name** will be pre-filled depending on organization profile)

**Comment by tschaffter** [comment]
The forms look great. For suggesting edits, should we ask for the Challenge ID/Slug and Organization Login to uniquely identify them?

**Comment by vpchung** [comment]
Good idea - I'll use those unique identifiers.

**Comment by vpchung** [comment]
Forms have been completed and shared with the OC group.

Closing ticket now.
