### ISSUE TITLE
[Feature] Improve “Recently Launched” filter

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1871]
### What projects is this feature for?

OpenChallenges

### Description

One of the sorter for challenges is "Recently launched". The current implementation takes all the challenges whose start date is in the past and sort them so that the closer the start date is from today, the higher it will rank in the results.

There are a few issues with this approach:

- the results may include challenges that have started a long time ago, so they are not really "recently" launched
- the results may include closed challenges

One improvement would be to rename the sorter to "Start date (most recently)" to make it clearer that the sorting is done based on the start date. But shall we keep displaying only challenges that have already started?

Another options would be to create a filter that shows only all challenges that have started recently, which may require use to define what "recently" means (e.g. within the past 3 months).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
## Update 2023-08-28

This ticket requires to redesign how we want to filter challenges based on their start and end date.

The process we should follow:

- Review the existing behavior of sorting challenges based on their start and end date
- Identify what the expected behavior should be
- If the actual and expected behavior are different, come up with an implementation plan.

We won't have the time to work on this ticket this sprint.

Moving to Sprint 23.09.

**Comment by rrchai** [comment]
- Hide "Most Stars" from the sort menu
- Improve the "Closing/Starting soon" and "Recently Launched/Completed" sorter - filtering by 3-month window and corresponding status
