### ISSUE TITLE
[Feature] Add Graphical timeline of all challenges to the Home page

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1873]
### What projects is this feature for?

OpenChallenges

### Description

The motivation is to explain why tracking challenges are relevant => large increase in the number of challenges over time, more difficult to track, hence why we created OpenChallenges.

One plot that Paul suggested is a bar plot over time where the height of the bar show the number of challenges organized in Year Y. If we can make the plot dynamic, we could show the fraction of challenges that are active, completed and upcoming.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
@jaybee84 @rrchai Have you generated a plot like the one described above when you worked with the challenge landscape data?

**Comment by rrchai** [comment]
@tschaffter I like Paul's idea to have a nice visualization to showcase the challenges growth over time. I haven't made such plot for the challenges before. We could start using js library to make an interactive & dynamic time-series plot and annotate the big achievement (e.g. OC launched). Besides the `status` of challenges, `platform` is also a good filter on the plot.

**Comment by tschaffter** [comment]
@chepyle I remember that one of your presentations had a plot that was describing one aspect of the evolution of challenges over the years. Was it the increasing number of participants per challenge? Do you have any impactful plot that we could show as a static figure at first? We could later replace it by a dynamic plot that is generated from live OC data.

**Comment by tschaffter** [comment]
Here is how to use Plotly, which could have been an option too?

- https://medium.com/@davidjohnakim/using-plotly-js-with-angular-7fc07ca9a48f
- https://github.com/plotly/angular-plotly.js/blob/master/README.md

Thanks @sagely1 for sharing this!

So far EChart looks great for our use case!
