### ISSUE TITLE
[Feature] Filter organizations by challenge id (backend)

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/sage-monorepo#1874]
### What projects is this feature for?

OpenChallenges

### Description

Currently, the organization can be filtered by challenge contribution roles, but lack of feature to filter by specific challenge id.

Request to enable to filter organizations by specifying challenge id.

### Anything else?

This feature will support the ticket #1537.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rrchai** [comment]
complete via #1824

**Comment by rrchai** [comment]
Move to Backlog since we could get the challenge contributors via `https://dev.openchallenges.io/api/v1/challenges/1/contributions`. Filtering orgs by challenge id is needed for #1537

**Comment by tschaffter** [comment]
@rrchai Should this task be closed if no longer required?

**Comment by rrchai** [comment]
@tschaffter Yeah, let's close it.
