### ISSUE TITLE
[Story] Build and publish Sage Monorepo Docs with MkDocs Material

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1876]
### As a user, I want

As a Developer, I want the documentation of this monorepo to be visible and accessible so that I can quickly locate the information I need.

### Description

In #1735, we have identified that we want to publish the Sage Monorepo docs in Markdown format with [MkDocs](https://www.mkdocs.org/)/[MkDocs Material](https://squidfunk.github.io/mkdocs-material/).

The goal of this story is to create a GitHub workflow that builds and publish the Markdown files with MkDocs to GitHub Pages. The files to consider are:

- `docs/*.md`
- `apps/**/README.md`
- `libs/**/README.md`
- `README.md`

An example of GitHub workflow is provided by the Trivy project here:

- https://github.com/aquasecurity/trivy/tree/main/docs
- https://github.com/aquasecurity/trivy/blob/main/.github/workflows/test-docs.yaml
- https://github.com/aquasecurity/trivy/blob/main/.github/workflows/mkdocs-dev.yaml
- https://github.com/aquasecurity/trivy/blob/main/.github/workflows/mkdocs-latest.yaml

### Acceptance criteria

- The Markdown files are visible on GitHub Pages

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Tentatively assigning to Verena

**Comment by vpchung** [comment]
Resolved with #2409
