### ISSUE TITLE
Add short description to each section of the organization profile page

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#1906]

**Comment by vpchung** [comment]
[PR](https://github.com/rrchai/sage-monorepo/pull/2) made to Rong's feature branch

**Comment by vpchung** [comment]
## Preview

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/ac913ea5-9021-419e-9c94-ec545ef4d94c)
![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/18c871b0-675c-4dcd-9ede-0e5f749e4382)

**Comment by rrchai** [comment]
- complete via https://github.com/rrchai/sage-monorepo/pull/2
