### ISSUE TITLE
[Bug] Use the same width for challenge and org cards

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What projects are you seeing the problem on?

OpenChallenges

### Current behavior

Home page: the spacing between featured challenges looks good

<img width="1436" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/5619219d-5cfc-4d0d-8c5a-d76eda392939">

Home page: the spacing between organizations does not look consistent with the spacing used for challenges.

<img width="1432" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/067ee826-b91d-4b99-be11-a9b68ae8c32b">

### Commit ID

35d5a8f82b12b81ee56f093beb5f93ba3b3ec3b7

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
@rrchai The latest version of `main` reduces the spacing between organizations. This spacing is still slightly larger than between featured challenges.

**Comment by rrchai** [comment]
@tschaffter  The width of challenge card and org card is different. That's why the gaps are different. The container of card group should be the same width.

**Comment by tschaffter** [comment]
What about making the width of the challenge card the same as the org card width - or vice versa depending on design constrains - so that the app using a single card width to increase consistency and simplify the layout?
