### ISSUE TITLE
[Bug] Challenge search page: inconsistent space for 2 cards per row

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What projects are you seeing the problem on?

OpenChallenges

### Current behavior

Here is an example with a correct layout:

<img width="1440" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/3590f24d-f790-41d0-9bb8-3e97aa65dfa1">

When selecting the "upcoming" challenges (2 results), the second card is not at the same location as the second card in the above example.

<img width="1440" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/c0478179-0653-457b-a225-2cc04d687f8b">

This issue may also affect the organization search page.

### Expected behavior

See above

### Commit ID

a0a3c57d9e81df9ce9a68abdda667fe71c6d3f3c

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rrchai** [comment]
Thanks for catching the bug!
