### ISSUE TITLE
[Feature] Add information banner at the top of the OC home page

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1936]
### What projects is this feature for?

OpenChallenges

### Description

I propose to add a banner on the top of the home page to say that this is a preview of the DB and that a comprehensive release of the DB will occur sometimes in September. We can also say that organizations are welcome to contact us to ensure that their challenge data are comprehensive.

Implementation ideas:

- A [card](https://material.angular.io/components/card/overview)
- Or maybe a component from the other UI library we use pagination (I forgot the name)

The text to include in the card will be added to this ticket shortly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
Version 1 (pending validation):

---
**Welcome to OpenChallenges!**

This website uses a preview of the OC Database. We are working hard to update the DB with more challenge data. The comprehensive DB will be released in September or October 2023. We encourage organizations to submit new challenges and update existing ones to ensure that their challenge data are comprehensive.
---

**Comment by vpchung** [comment]
Thanks, @tschaffter !  

Will we need to explain what OC stands for?  (I mean, it's straightforward to me... but maybe not to everyone?)

> **Welcome to OpenChallenges (OC)!**
>
> This website uses a preview of the OC Database...
