### ISSUE TITLE
[Bug] Duplicate contributors 

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#1947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What projects are you seeing the problem on?

OpenChallenges

### Current behavior

When an organization has multiple roles for a challenge, they are displayed multiple times with no explanation why, e.g. MJFF contributed as a challenge organizer, data contributor, and sponsor to [this challenge](https://openchallenges.io/challenge/27?tab=contributors), and so, shows up 3 times:

![Screenshot 2023-08-07 at 3 34 29 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/4168c064-162d-4bb1-9200-026ca51e4882)

To an unsuspecting user, this may seem like a bug.

### Expected behavior

Until we can add categorization, I suggest we add a unique filter or something similar, so that organizers are displayed only once.

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vpchung** [comment]
In response to #2118, @rrchai can you let me know whether the controller already handles "duplicate" organizations for a challenge?  I think the reason why an organization may display more than once is due to having multiple roles but please correct me if I'm wrong!

**Comment by rrchai** [comment]
> can you let me know whether the controller already handles "duplicate" organizations for a challenge? 

I don't think so, as I do see the endpoint getting contributions returns duplicates for the challenge.

>  I think the reason why an organization may display more than once is due to having multiple roles 

@vpchung This is correct

> Until we can add categorization, I suggest we add a unique filter or something similar, so that organizers are displayed only once.

I agree.
