### ISSUE TITLE
[Data] Add the platform Nightingale OS and its challenges to OC

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1953]
### What projects is this feature for?

OpenChallenges

### Description

Shared by @LucaFoschini

https://app.nightingalescience.org/contests

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vpchung** [comment]
@tschaffter there is a section in our [draft SOP on how to add platforms](https://docs.google.com/document/d/1wLRtNvhsC_MlvIWjRdpH2yoErgUYgvm4diYgtdzC3d8/edit#heading=h.2h4al2fo3q9x).  It would be great if you could try out the steps to ensure they are comprehensive and easy to follow.

Thanks!

**Comment by tschaffter** [comment]
@vpchung I can do that!

**Comment by tschaffter** [comment]
I submitted the platform and two challenges via the Google form. As @vpchung suggested, internal data curator should input the data directly into the OC DB (spreadsheet) to avoid extra work.

**Comment by tschaffter** [comment]
Done
