### ISSUE TITLE
[Feature] Fit org logos into the round avatar

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1955]
### What projects is this feature for?

OpenChallenges

### Description

We have org logos that are cropped by the circular mask of the avatar component, while others look fine.

Example:

<img width="1436" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/87ed145a-b0fd-44d8-aa9e-4fe0815ab303">

Logos should ideally not be cropped as this amounts to modifying them.

For the logos that are cropped, we could

1. Modify the original image file so that the logo fits into a circular mask.
2. Check if there are Thumbor filters that can add padding (there is at least one developed by the community, though it is no longer maintained) or can achieve a similar effect (e.g. fit-in, resize)
3. Use CSS to add padding

Option 2 and 3 would require us to capture additional information in the OC DB (e.g. padding value). However, this should be easier to update than updating the original image file (Option 1).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
LinkedIn [organization API model](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/organization-lookup-api?view=li-lms-2023-09&tabs=http) includes information about how to crop the (original) image.

**Comment by tschaffter** [comment]
@rrchai Can you please save the result of your exploration here before closing this ticket?

**Comment by tschaffter** [comment]
This ticket has been timed box at the end of the Sprint 23.09.

**Comment by rrchai** [comment]
## Thumbor Exploration

### Smart Cropping
Thumbor's [Smart Cropping](https://thumbor.readthedocs.io/en/latest/usage.html?highlight=smart#smart-cropping) uses `OpenCV ` to detect an image's object and define the focal point for cropping based on the center of the object. 

I have encountered the error in the Thumbor container (`Cannot find `opencv` module`) while applying `smart` to the image url during my initial testings, so I updated the thumbor image to install `opencv` (see #2229). However, I am now able to load the "smart" image, even if the Thumbor container doesn't have `opencv` installed. Anyways, I tested both [feature](https://thumbor.readthedocs.io/en/latest/detection_algorithms.html#feature-detection) and [facial](https://thumbor.readthedocs.io/en/latest/detection_algorithms.html#facial-detection) detection/cropping using Thumbor's smart, here are some results: 

#### Logo - feature

_Original size is 66 x 79._

```console
http://localhost:8000/img/unsafe/200x200/logo/fda.svg
```
<img width="222" alt="Screen Shot 2023-10-13 at 10 03 14 AM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/73901500/9df284a3-8db5-49c4-849e-84f89ab9238f">

```console
http://localhost:8000/img/unsafe/200x200/smart/logo/fda.svg
```
<img width="222" alt="Screen Shot 2023-10-13 at 10 03 14 AM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/73901500/9df284a3-8db5-49c4-849e-84f89ab9238f">

```console
http://localhost:8000/img/unsafe/200x50/smart/logo/fda.svg
```
<img width="222" alt="Screen Shot 2023-10-13 at 11 28 56 AM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/73901500/dff03ac5-23f4-4262-918c-11b658ccf1df">

#### People - facial

_Original size is 206 x 205._

```console
http://localhost:8000/img/unsafe/200x200/team/rong.png
```
<img width="200" alt="Screen Shot 2023-10-13 at 11 00 04 AM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/73901500/f545851e-55b1-4763-95c9-a9d30531bb06">

```console
http://localhost:8000/img/unsafe/200x50/smart/team/rong.png
```
<img width="200" alt="Screen Shot 2023-10-13 at 10 59 28 AM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/73901500/ea221427-7832-4599-9779-a7fd8c440529">

### Manual Cropping


--- 
The takeaways on my exploration for Thumbor:
- It seems the `smart` is not working to "smart" detection and cropping the image on my end. I expect at least my face would be cropped to fit in the center of (200x50) image. Or I miss something to enable the "smart"? But there's no further errors in the thumbor container and the image can be loaded successfully.
- The thumbor would fill up the space with the average color from the image ("grey" in the logo image)
-

**Comment by tschaffter** [comment]
> http://localhost:8000/img/unsafe/200x50/smart/team/rong.png

@rrchai Thumbor applies operation from left to right, so in the case of your photo, it will crop (or fit?) the image into 200x50, then apply smart detection. Instead, you should probably start with smart detection, and only then apply operations to change the size of the image. The easiest way to test that is to apply smart detection without including resize operation, e.g. `http://localhost:8000/img/unsafe/smart/team/rong.png`

**Comment by rrchai** [comment]
## Thumbor's Manual Cropping

The manual cropping is executed by defining the viewpoint position in this format: `{left}x{top}:{right}x{bottom}`.

For example, if we like to move the 200x200 logo into the center manually, we can define the viewpoint window like:

```console
http://localhost:8000/img/unsafe/0x30:200x100/fit-in/200x200/logo/fda.svg
```
<img width="256" alt="Screen Shot 2023-10-13 at 3 39 17 PM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/73901500/ce981884-cc7c-4901-bd3d-891c60c96b38">

Or moving my face to center in a 50 height: 
```console
http://localhost:8000/img/unsafe/0x30:200x80/fit-in/200x200/team/rong.png
```
<img width="235" alt="Screen Shot 2023-10-13 at 3 39 53 PM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/73901500/b8a2229f-8141-4483-b363-a8354529f41b">

The `fit-in` here is to stop Thumbor auto cropping, otherwise it will crop based on the focal point.

**Comment by tschaffter** [comment]
> Based on the focal points in the debugging result, my face is not fully recognized.

We should stick to example image, e.g. the images used on https://thumbor.readthedocs.io/en/latest/detection_algorithms.html. :-)

**Comment by rrchai** [comment]
## Thumbor's other features:

- The Thumbor will fill up the space (for upscaling) with the average color from the image ("grey" in the logo image), but you can define the fill color by applying `fill()`
    ```console
    https://dev.openchallenges.io/img/unsafe/200x200/filters:fill(red,1)/logo/fda.svg
    ```
   <img width="237" alt="Screen Shot 2023-10-13 at 3 52 43 PM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/73901500/801b69e6-5fb4-447a-b14b-58f5d050fbf7">

**Comment by rrchai** [comment]
> We should stick to example images when exploring tech, e.g. the images used on https://thumbor.readthedocs.io/en/latest/detection_algorithms.html. :-)

Right~ Love to see if the example image works. @tschaffter How can view the external image using url? `https://dev.openchallenges.io/img/unsafe/https://thumbor.readthedocs.io/en/latest/_images/face_detection_original.jpg` is not working, or do we have to upload it to aws bucket?

**Comment by rrchai** [comment]
Considering this task has been timed box, we can save the curiosity when we return to improving avatars. My thought is we could wait until we develop the feature, which enables to adjust image position in the avatar when users upload or edit avatars. So we could go back to fix the logos by moving the logo to center of avatar in the app :).

Please feel free to close the task or move it to backlog~ @tschaffter

**Comment by tschaffter** [comment]
Thanks for exploring and documenting so well your findings!
