### ISSUE TITLE
[Docs] Tag OC EC2 for development with new CostCenter values

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2017]
### What projects is this documentation issue for?

OpenChallenges

### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

## Tasks

- Update the `CostCenter`  with a value from this [docs](https://sagebionetworks.jira.com/wiki/spaces/IT/pages/2553544733/Finance+Program+Codes)
- Create the tag `CostOwner` and set it to our Sage email address

Team members who have completed the update:

- [x] Thomas
- [x] Verena
- [x] Rong
- [x] Maria

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vpchung** [comment]
Do we need to update this if the number is the same?

![Screenshot 2023-08-26 at 9 26 52 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/c36ecada-1a2a-4099-b2a3-d7ed691ae14b)
