### ISSUE TITLE
Explore LOAD LOCAL INFILE for inserting data?

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#2047]
## Motivation

Our current process of updating the database tables is:

1. export the Google Sheets as CSV
2. run a Python script that will clean up the data and reformat it to something SQL will accept, e.g.

   **Before**
   ```python
           id                                          name                                          slug  ...            createdAt            updatedAt _validSlug
   0        1      Network Topology and Parameter Inference      network-topology-and-parameter-inference  ...  2023-06-23 00:00:00  2023-08-09 08:42:17       True
   1        2                       Breast Cancer Prognosis                       breast-cancer-prognosis  ...  2023-06-23 00:00:00  2023-07-26 19:47:13       True
   2        3          Phil Bowen ALS Prediction Prize4Life          phil-bowen-als-prediction-prize4life  ...  2023-06-23 00:00:00  2023-07-26 19:47:15       True
   ..     ...                                           ...                                           ...  ...                  ...                  ...        ...
   ```

   **After**
   ```txt
   (
       1,
       'network-topology-and-parameter-inference',
       'Network Topology and Parameter Inference',
       '',
       'Participants are asked to develop and/or apply optimization methods, including the selection of the most informative experiments, to accurately estimate parameters and
    predict outcomes of perturbations in Systems Biology models.',
       'https://www.synapse.org/#!Synapse:syn2821735',
       'completed',
       'intermediate',
       '1.0',
       '',
       '2012-06-01',
       '2012-10-01',
       '2023-06-23 00:00:00',
       '2023-08-09 08:42:17'
     ),
     (
       2,
       ...
   ```

3. copy-paste the results to the SQL file in challenge-service or organization-service

This ticket will focus on step 3, in particular: rather than continuing to edit the SQL file(s), we can import the data into the tables directly from flat file(s).  This can be achieved by refactoring the current SQL script to utilize the `LOAD LOCAL INFILE` function, e.g. from

```
INSERT INTO challenge (
    id,
    slug,
    name,
    headline,
    description,
    website_url,
    status,
    difficulty,
    platform_id,
    doi,
    start_date,
    end_date,
    created_at,
    updated_at
  )
VALUES (
  ...
);
```

to

```
LOAD DATA INFILE 'challenges.txt' INTO TABLE challenge
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\r\n'
  IGNORE 1 LINES;
```

## Things to consider

* `LOCAL` works only if the server and your client both have been configured to permit it. @tschaffter - here is a writeup on the [security considerations for LOAD DATA LOCAL](https://dev.mysql.com/doc/refman/8.0/en/load-data-local-security.html)
   * by default, `local_infile` is disabled on the server; we will need to update this if we want to move forward with this refactor
   * by default, the client library in MySQL binary distributions is compiled with ENABLED_LOCAL_INFILE disabled; we will additionally need to reconfigure the client with [ENABLED_LOCAL_INFILE](https://dev.mysql.com/doc/refman/8.0/en/source-configuration-options.html#option_cmake_enabled_local_infile) enabled

**Comment by tschaffter** [comment]
This [discussion](https://stackoverflow.com/questions/68090017/how-to-enable-the-mysql-connection-string-enable-local-infile-when-using-flywa) seems to include all the information we need.

Server: the project `openchallenges-mariadb`
Client: the project `openchallenges-challenge-service`

@vpchung Let's divide and conquer! Can you please open a feature branch and update the configuration of the server? I will then update the configuration of the client.

**Comment by tschaffter** [comment]
References for the client (i.e. the microservices):

- https://stackoverflow.com/a/56731634

I tried the above solution but the org service is then unable to access the MariaDB instance:

```console
SQL State  : 42000
Error Code : 1044
Message    : Access denied for user 'organization_service'@'%' to database 'organization_service&allowLoadLocalInfile=true'
```

**Comment by tschaffter** [comment]
@vpchung Here are [instructions](https://bobcares.com/blog/how-to-enable-local-infile-in-mysql/) that should help you configure the MariaDB instance to enable local infile. The instructions are for MySQL but hopefully they apply to MariaDB too. You could then use an sql CLI to validate that the feature works.

Once the server is properly configured, I will update the PR to enable the feature for the challenge and organization services.

**Comment by vpchung** [comment]
I enabled local_infile on the server (as well as updated the .env files) but still get the same error as you:

![Screenshot 2023-09-19 at 5 06 33 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/4c33f5ea-dc64-4ef0-a925-79537aea7765)

```sql
SQL State  : 42000
Error Code : 1044
Message    : Access denied for user 'challenge_service'@'%' to database 'challenge_service&allowLoadLocalInfile=true'
```

Here I'm showing the logs for challenge-service.

**Comment by vpchung** [comment]
Thanks, @tschaffter - that fixed the issue and I can now start using `LOAD DATA LOCAL INFILE` 🎉

**Comment by vpchung** [comment]
## 9/20 update

I am now working on refactoring the challenge-service's `insert-data.sql`, one statement at a time.  Starting with the `challenge_platform` table, the statement has been updated to:

```sql
LOAD DATA LOCAL INFILE 'platforms.csv' INTO TABLE challenge_platform
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\r\n'
  IGNORE 1 LINES;
```

The table is unfortunately empty, and looking at the openchallenges-challenge-service logs, it is due to `platforms.csv` not being found:

```
** BEGIN NESTED EXCEPTION ** 

java.io.FileNotFoundException
MESSAGE: platforms.csv (No such file or directory)

STACKTRACE:
...
```

I then tried using the absolute path (`/workspaces/sage-monorepo/apps/openchallenges/challenge-service/src/main/resources/db/migration/platforms.csv`) but it was also a no-go.  @tschaffter do you happen to know where the filepath should start for the openchallenges-challenge-service?

Furthermore -- I don't know if this is related and/or will later be encountered after the filepath issue is addressed -- I also tried running the statement above directly in SQL and got the following error:

**Statements**
```txt
USE challenge_service;
LOAD DATA LOCAL INFILE '/workspaces/sage-monorepo/apps/openchallenges/challenge-service/src/main/resources/db/migration/platforms.csv' INTO TABLE challenge_platform
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\r\n'
  IGNORE 1 LINES;
SELECT * FROM challenge_platform;
```

**SQL Console**
```txt
As a result of LOCAL INFILE command server wants to read /workspaces/sage-monorepo/apps/openchallenges/challenge-service/src/main/resources/db/migration/platforms.csv file, but as of v2.0 you must provide streamFactory option returning ReadStream.
```

Looking around the 'net, I can see that we could possibly [implement a workaround](https://mariadb.com/kb/en/importing-csv-file-to-mariadb/), but I will not do this until I know for sure that openchallenges-challenge-service also encounters the same issue.

**Comment by vpchung** [comment]
Per @tschaffter 's suggestion, the root folder of each microservice most likely starts at the microservice's `src` or java folder.

After trying several different filepaths with no success, I went into the challenge-service container and found that the filepath to the flat file is `/workspace/BOOT-INF/classes/db/`. Tried using this and the error is now gone! 🎉 

But the table is still empty.  To be further investigated........

**Comment by vpchung** [comment]
Looking at the logs, I couldn't find anything useful or that would point me to an error with the statement.   I thought about trying to populate another table before `challenge_platform` so I moved one of the statements up:

```
-- challenge_input_data_type

INSERT INTO challenge_input_data_type (id, slug, name)
VALUES (1, 'genomic', 'genomic'),
  (2, 'proteomic', 'proteomic'),
  (3, 'gene-expression', 'gene expression'),
  (4, 'metabolomic', 'metabolomic');

-- challenge_platform data

LOAD DATA LOCAL INFILE '/workspace/BOOT-INF/classes/db/platforms.csv' INTO TABLE challenge_platform
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\r\n'
  IGNORE 1 LINES;
```

`challenge_input_data_type` populated just fine, but `challenge_platform` is still empty :upside_down_face: Again, the logs do not provide anything useful, at least not that I could find.

**Comment by vpchung** [comment]
Found the bug - the statement was using `/r/n` as the line terminator (something I'm used to using at my previous job) but there are no carriage returns in the `platforms.csv` file 🤦‍♀️

Using just `/n` worked perfectly!
![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/df2ab547-9748-4a09-b144-fc16db417d24)

No longer blocked.

**Comment by tschaffter** [comment]
> Using just /n worked perfectly!

@vpchung I think you mean `\n` 😆
