### ISSUE TITLE
[Feature] Increase the coverage of OC organization service to >30%

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2063]
### What product(s) is this feature for?

OpenChallenges

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
Added to Sprint 23.10

**Comment by mdsage1** [comment]
#2348 improved overall coverage to 15% and exception coverage to 100%

**Comment by tschaffter** [comment]
@mdsage1 Can you please add an update to this ticket? We usually do it like this:

```
## Update yyyy-mm-dd

Description of where this ticket stands, whether there are blockers, expected completion date.
```

**Comment by mdsage1** [comment]
## Update 2023-12-04

[PR](https://github.com/Sage-Bionetworks/sage-monorepo/pull/2348) https://github.com/Sage-Bionetworks/sage-monorepo/pull/2348 approved on 12-04-2023 improving unit test coverage for exceptions to 100%.
[PR](https://github.com/Sage-Bionetworks/sage-monorepo/issues/1528) is pending as well as the implementation of additional unit tests to reach > 30% coverage in org service.
Current organization service unit test coverage is now  15%.

### Blockers
[Using a test database for unit tests](https://www.testrail.com/blog/unit-test-database/)
Will need to determine the appropriate way to either Mock the database or use another method before unit tests can be implemented for the classes related to the database.

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/122999770/335e0966-ca6e-4627-80f4-1ac5b0773e90)

**Comment by tschaffter** [comment]
> Current organization service unit test coverage is now 15%.

The reference is the value in the CODE QUALITY dashboard (9.5%).

> [Using a test database for unit tests](https://www.testrail.com/blog/unit-test-database/)

I will take over this ticket or assign it to a backend engineer if we can get access to one next year. For now I'm adding this ticket back to the backlog.

**Comment by tschaffter** [comment]
Added to backlog

**Comment by tschaffter** [comment]
Added to Sprint 23.12

**Comment by mdsage1** [comment]
## Update 2023-12-08

PRs, #2348 and #2388, have been merged to address unit testing in organization service.
Overall coverage increased to 12.2% for organization service after #2388 was merged. 
![image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/122999770/70f11e5f-4731-475c-8fb1-b851c4430e73)

**Comment by tschaffter** [comment]
Added to Sprint 24.1

**Comment by tschaffter** [comment]
@mdsage1 Can you please provide an update on this ticket and when it could be completed?

**Comment by tschaffter** [comment]
@mdsage1 I will take over this task, which I think you almost complete.

**Comment by tschaffter** [comment]
Added to Sprint 24.2

**Comment by mdsage1** [comment]
@tschaffter Please review PR #2389 so that I can document the updates to the coverage that resulted from the unit tests I wrote. These updates should be what's needed to push coverage of OC organization service above 30% but cannot be verified until the PR has been reviewed again. Your suggested changes were implemented ~1 month ago.

**Comment by tschaffter** [comment]
The PR #2389 has been merged. Thanks!

**Comment by mdsage1** [comment]
PR #2389 only increased code coverage by 0.1% which seems misaligned with expectations. The new coverage is at 12.3%. @tschaffter plans to investigate what factors impact this.

**Comment by mdsage1** [comment]
Overall coverage increased to 17.1% for organization service after #2389 was merged.

![image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/122999770/462f6613-b23f-4d05-ada2-0974554ac6a4)

**Comment by tschaffter** [comment]
## Update 2024-02-23

Reopening now that we can get the coverage value from Sonar and that this value is below the target (30%). @mdsage1 will investigate where the discrepancy come from.

**Comment by tschaffter** [comment]
Added to Backlog

**Comment by mdsage1** [comment]
## Update 2023-03-18
The latest Sonar Code Quality Report indicates that organization-service coverage is 22.6%. No new unit tests have been added. 
![image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/122999770/175755bd-3eb7-4ed4-b5ec-b4e7293886c8)
