### ISSUE TITLE
[Epic] Add constraints to all the properties of the OC Data and API models

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2064]
### What product(s) is this story for?

OpenChallenges

### As a user, I want

As an OC Team Member, I want the quality of the data to be validated so that the data that users discover in the OC app are of high quality.

Tasks:

- Review all the properties of the OC data model and identify suitable constraints for them.
- Add constraints to the Data model (SQL)
- Add constraints to the API model

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Add to Sprint 23.10 (initially planned to spread over 23.09 and 23.10)

**Comment by tschaffter** [comment]
@vpchung Can you please post an update about this ticket based on recent discussions (Slack, stand up, 1:1)?

**Comment by tschaffter** [comment]
Added to Sprint 23.11

**Comment by tschaffter** [comment]
@vpchung Can you please add an update to this ticket?

**Comment by vpchung** [comment]
### 12/4 update

Json schema has been implemented, and I can add the constraints to the SQL tables and API models this week.

**Comment by tschaffter** [comment]
Added to Sprint 23.12
