### ISSUE TITLE
[Docs] Enable external developers to contributes to Sage Monorepo

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2080]
### What product(s) is this documentation issue for?

Sage Monorepo

### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Description

Sage is expected to hire (GenUI) software engineers to contribute to Agora and Schematic. The goal of this ticket is to explore how to enable these engineers to contribute to projects in Sage Monorepo with the best DX that Sage can offer.

Developing remotely on an EC2 or Codespace provides the following DX benefits.

- Faster inbound and outbound internet traffic than when using "regular" internet connection
  - Download speed up to 30-40 times faster than the slowest internet connection among the OC team members (see [results](https://github.com/Sage-Bionetworks/sage-monorepo/blob/main/docs/develop-on-a-remote-host.md#use-case)) => Fast download of npm/Java/Python/R/Docker artifacts (still limited by the outbound speed of the package registries)

See [Sage Monorepo - Uniformizing Developer Experience](https://docs.google.com/presentation/d/1V3itoy5zCiUbuH_XxkO0ypMq7lHRhznMvKP-9J8t9jM/edit#slide=id.g13c0b408921_0_0) for more benefits

Questions:

- Can Sage provide external engineers with an EC2 instance created with Sage Service Catalog? @brucehoff
  - Can the engineers turn on/off the instance by themselves when needed to reduce cost?
- To what extend can we leverage the free quota offered by GitHub Codespace? @tschaffter 
  - Compare free and pro ($4/mo) GitHub accounts
- What are the compute resources that external developers bring with them?

Ccs:

@milen-sage @sagely1 @brucehoff @jay-hodgson 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brucehoff** [comment]
> Can Sage provide external engineers with an EC2 instance created with Sage Service Catalog?

Service Catalog is intended to be a place for scientists (Sage workers and external collaborators) to do data analysis on sensitive data securely.  I think a better solution for providing compute for software developers is to use GitHub runners, either supplied by GitHub or (if those runners are not sufficient) to provision our own runners and connect them to GitHub.

Also, I would expect any contracted software developer to provide their own development resources.  It's not clear to me why Sage would provide cloud compute resources for a contracted developer to work.

**Comment by tschaffter** [comment]
## Update

I gave additional context to Bruce about why the OC team members are developing on EC2 instance.

Technically it's possible to give external collaborators access to the Sage Service Catalog, though the UX has not been designed for them. E.g. they would be asked to specify cost center code, which they would not know about unless specifically told.

The Sage team responsible for the project that hires the contractor would also be responsible for providing IT support to the contractor regarding the EC2 instance, which should be factored when thinking about using the service.

Bruce and I agree that a contractor should be responsible for having access to sufficient compute resources, including the internet connection.

Other insights from Bruce:

- We could use GitHub Codespace instances and Sage would pay for the compute resources used in addition of the monthly quota. However, a review I conducted revealed that Codespace is more expensive hourly that when using equivalent EC2 instances.

About custom GitHub runners:

- I could ask IT to provision a larger running if needed (no longer free even for public projects)
- One question is how using a custom GH runner would affect developers who use a fork?
- Sage may have used a custom GH running in the past to build Synapse API Client for Python on MacOS version not supported by GH.
