### ISSUE TITLE
[Data] Update CAGI challenge data in OpenChallenges

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2109]
### What product(s) is this feature for?

OpenChallenges

### Description

Tasks:

- [ ] Review/update the pages of the [CAGI challenges](https://openchallenges.io/challenge?platforms=cagi)
- [ ] Add new CAGI challenges that are not yet in OC
- [ ] Consider adding CAGI as an Organization (similarly to CAMI)

Resources:

- [OC Data Contribution SOP (draft)](https://docs.google.com/document/d/1wLRtNvhsC_MlvIWjRdpH2yoErgUYgvm4diYgtdzC3d8/edit)

### Anything else?

@gaiaandreoletti Please reach out to Verena if you have any questions related to the collection and curation of data.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gaiaandreoletti** [comment]
- [x] #2109

**Comment by tschaffter** [comment]
I can find the CAGI org in the latest version of OC (not yet in production).

**Comment by gaiaandreoletti** [comment]
it is listed in the excel file. Not sure what else needs to be done. @vpchung  can you help please?

**Comment by vpchung** [comment]
@gaiaandreoletti I think what Thomas meant was that the data is there, but we haven't pushed the db changes to production yet.  We should be good!
