### ISSUE TITLE
[Data] Add CausalBench Challenge to OC DB

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2120]
### What product(s) is this feature for?

OpenChallenges

### Description

This challenge was [suggested by Luca](https://www.linkedin.com/posts/patrick-schwab_the-causalbench-challenge-a-machine-learning-activity-7102816057945387009-VqPv/?utm_source=share&utm_medium=member_desktop) on LinkedIn.

Tasks:

- [ ] Add the challenge to OC DB
- [ ] Make the data available in prod
- [ ] Reply to Luca's comment on LinkedIn

Resources:
- [Manuscript](https://arxiv.org/abs/2308.15395) (doi)
- https://www.gsk.ai/causalbench-challenge/
- https://eval.ai/web/challenges/challenge-page/1981/overview (platform)
- GitHub
  - https://github.com/causalbench/causalbench
  - https://github.com/causalbench/causalbench-starter

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vpchung** [comment]
Completed with #2119

**Comment by tschaffter** [comment]
I realize that we don't have Eval.ai as a platform, which is used by this challenge.
