### ISSUE TITLE
[Story] Add Grafana and Prometheus to monitor OC

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#216]
### What projects is this story for?

OpenChallenges

### As a user, I want

As an engineer, I want to have an easy access to the logs generated by the components of the stack so that I can quickly determine whether the stack is healthy.

### Description

The goal of this story is to add Graphana and Prometeus to the OC stack to centralize the logs generated by the different components of the stack.

### Acceptance criteria

- Graphana and Prometeus have been added to the stack and can be deployed with Docker.
- Two services or more have been configured to store their logs with Graphana and Promoteus.

### Tasks

- [x] #217
- [x] #218
- [x] #219
- [x] #1343
- [x] #1344

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by thomasyu888** [comment]
Its unfortunately that Tess isn't here, because she setup Promethius + grafana to monitor the Toil cluster workflow engine set up in 2019.  She did also use this tool to pair with Promethius for alerts I think: https://github.com/google/mtail.  I'll watch this ticket for your exploration results!

**Comment by tschaffter** [comment]
Grafana and Prometheus are now part of the OC stack. To start Grafana and all the components required to collect data - mainly Prometheus and mysqld-exporter:

```console
nx serve-detach openchallenges-grafana
```
