### ISSUE TITLE
[Feature] <Add Research to the People as organization>

### ISSUE THREAD

**Issue by gaiaandreoletti** [Sage-Bionetworks/sage-monorepo#2169]
### Description

I have added some hackathons from this new organization to the OpenChallenges Data file 
this is their logo. Would be great to add them to the Organization's list.
Thank you @vpchung!

### Anything else?

<img width="405" alt="Screen Shot 2023-09-27 at 9 09 46 PM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/46945609/9dbee19f-62f8-4f4f-b4bd-a546d9172d7d">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vpchung** [comment]
@gaiaandreoletti is this their website? https://rttp.stanford.edu/

**Comment by vpchung** [comment]
Also, can you check whether it's okay that I modified their org logo to square?

![research-to-the-people](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/59e0678d-943b-49c1-b85b-5e0fffc1c357)

**Comment by vpchung** [comment]
@gaiaandreoletti I have added them to the "[organizations](https://docs.google.com/spreadsheets/d/1XRSUVqbZk_k9_rV1vpgPVMQ0fVV0mavwY8Aqyy0C2HQ/edit#gid=1828426045)" sheet, pending description.

**Comment by gaiaandreoletti** [comment]
Yes, that's their website and yes the logo is perfect. thank you! @vpchung

**Comment by tschaffter** [comment]
The logo is smaller than the max size displayed on OC so it will look pixelated.
