### ISSUE TITLE
[Docs] Craft an official description of the three core concepts of OC

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2171]
### What product(s) is this documentation issue for?

OpenChallenges

### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Description

The three core concepts are introduced as metrics on the top of the home page. They are:

- challenge
- organizations & hosting societies
- challenge platforms

Discussions with stakeholders revealed that it was not always clear whether an "entity" was a platform and/or an organization.

The goal of this ticket is to craft descriptions for these three concepts. The description could be use as tooltips in the web app or printed on one of the pages.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
Tentatively assigning this task to @gaiaandreoletti to start with a fresh pair of eyes.

**Comment by gaiaandreoletti** [comment]
pasting here the core concepts description:

**Glossary**
**Challenge**: a call to take part in a contest or competition. Challenges are typically built on large and complex data sets, focused on scientifically impactful and timely research questions. They result in a set of solutions to the given problem, originating from groups and researchers all over the world.

**Benchmark**: systematic assessment of the performance of a variety of methods for a given task normally based on defined case studies and metrics.

**Platform**: any hardware or software used to host an application or service. (e.g. synapse, Drupal, etc.)

**Organization**: describe a research modality where diverse and independent researchers come together to focus on one or more limited sets of tasks.

**Comment by gaiaandreoletti** [comment]
@tschaffter @vpchung  @rrchai 

Some feedback during lunch post OC talk:

1) having the sage logo also in the Team page. It should be more prominent to recognize the effort Sage put.
2) Having benchmarking not only challenges in the portal so I suggest reframing the text as 

"OpenChallenges (OC) is a centralized hub for biomedical challenges and more, offering a benchmarking system that empowers participants with the most up-to-date information about relevant challenges, while providing organizers with standardized challenge event templates and intelligence."

**Comment by gaiaandreoletti** [comment]
- [ ] Meet our team page is outdated

**Comment by tschaffter** [comment]
> Meet our team page is outdated

This issue is tracked in #2197

**Comment by tschaffter** [comment]
> OpenChallenges (OC) is a centralized hub for biomedical challenges and more, offering a benchmarking system that empowers participants with the most up-to-date information about relevant challenges, while providing organizers with standardized challenge event templates and intelligence.

I think that the term "benchmarking system" may confuse the user by making them think that OC is a challenge/benchmarking platform, which OC is not.

**Comment by tschaffter** [comment]
@gaiaandreoletti Please add the descriptions from https://github.com/Sage-Bionetworks/sage-monorepo/issues/2171#issuecomment-1741235093 to a Google doc before inviting the OC team member to make suggestions.

Here is some feedback:

- Challenge: this description resonates with me. Maybe mention the terms "task" and "leaderboard" as an attempt to further standardize our vocabulary. Consider mentioning that a challenge is usually active for a fixed duration.
- Platform: we need a more tailored description. A platform could be described as a service that enable the organization of challenges. Potentially include the list of actions that platforms support, such as participant registration, evaluation of submitted methods, leaderboard generation, communication tools, etc.
- Organization: An organization in OC means https://en.wikipedia.org/wiki/Organization. The description could be "an entity such as a company, an institution, or an association comprising one or more people and having a particular purpose". Maybe the description could establish the relationship between an org and challenges, e.g. referring to orgs that contribute to a challenge as a member of its organizing committee or as a participating member (OC does not yet capture orgs that participated to challenges as participant).

**Comment by tschaffter** [comment]
@gaiaandreoletti I think that you created the Google doc but can't find it. Can you share the link to this thread?

**Comment by gaiaandreoletti** [comment]
@tschaffter here it is! https://docs.google.com/document/d/1T0DStWW06X9VOHZ7fUElaOmJKIKAsDYy_J5JZi1K8IA/edit?usp=sharing

**Comment by gaiaandreoletti** [comment]
@tschaffter updated link: https://docs.google.com/document/d/1XVfn3vGw3OsuATfhQVO281aV65wh0PI6/edit?usp=drive_link&ouid=106220044830802031009&rtpof=true&sd=true
 move it to the [OpenChallenges shared folder](https://drive.google.com/drive/u/1/folders/1Nhkl_VdtzYsy-ge2IdPacM-ldhynNcMh)

**Comment by tschaffter** [comment]
I created a native Google Docs [here](https://docs.google.com/document/d/1rIjVOUAwh8yuTBGynpMcvygtLwnPtLNRcvwLXETnLHE/edit) (instead of a Word doc)

**Comment by tschaffter** [comment]
Added to Sprint 23.11

**Comment by tschaffter** [comment]
I'm going to time box this issue and close it. The existing descriptions are available in [OpenChallenges Glossary](https://docs.google.com/document/d/1rIjVOUAwh8yuTBGynpMcvygtLwnPtLNRcvwLXETnLHE). More feedback would be required to use them in the app. Meanwhile, they already clarify for us what a challenge platform is.
