### ISSUE TITLE
[Design] Difficulty in identifying how soon a challenge starts or closes when using the new filters

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2185]
### What product(s) is this feature for?

OpenChallenges

### Description

Along with new filters like Starting Soon, Closing Soon, etc. we have a new sorter: by Start Date.

However, the challenge cards don't include any date information so it's difficult to identify how soon the challenges start/close or even if the sorting is done in ascending or descending order (we use future dates to past dates).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vpchung** [comment]
I thought of two options:

1. Move the status from the footer into the same space as the tagline/headline (left column).  One of the benefits of this is that it would allow there to be more space in the footer for the list of incentives.

2. Keep the status where it is (right column).

In both designs, there would be some allusion to the start/end date, either explicitly (top row) or implicitly (bottom row):

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/ad9eab87-5903-4ed6-810f-4d0c10dc30c7)

> [!NOTE]
> I have also removed the button border from the status (that Adam previously mentioned as a possible design flaw) and instead utilized a radio button to signify the status.

**Comment by vpchung** [comment]
@tschaffter @rrchai @gaiaandreoletti @mdsage1

**Comment by tschaffter** [comment]
I prefer Option 2, see notes below:

- Option 1 would increase the height of the card, so technically Option 2 should have a smaller height. I prefer Option 2 because the cards are more compact.
- I would remove the parenthesis and start the line with a capital letter: `(starts in 2 weeks)` => `Starts in 2 weeks`
- The format of the date `mm/dd/yyyy` used for active challenges make confuse non-US users. Instead we could use `Ends in 2 months|weeks|days`.

**Comment by vpchung** [comment]
### Latest iteration

![Screenshot 2023-10-12 at 11 31 57 AM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/dd3cf8e7-9610-46f7-a7c5-070dc0d03705)

**Comment by tschaffter** [comment]
Shall we get rid of the vertical space between the description and the card footer? Below is the production card for reference where the vertical space is not included. Unless it's part of the new design?

<img width="337" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/ee943d79-fb3c-49ff-b204-4923dfe0a4aa">

**Comment by vpchung** [comment]
> Below is the production card for reference where the vertical space is not included. Unless it's part of the new design?

The screenshots I provided are from our Figma mockups, which have not been updated to reflect the changes made in the app, thus explaining the extraneous space.

I will update the mockups in future iterations.

**Comment by tschaffter** [comment]
I like the new design. We can discuss the font size and line spacing as part of the implementation review process.

**Comment by vpchung** [comment]
Just for you, @tschaffter 😬 

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/5b804bf4-2372-431f-8eda-28d3b29cc952)

**Comment by tschaffter** [comment]
The implementation of the design change will be tracked in https://github.com/Sage-Bionetworks/sage-monorepo/issues/2240
