### ISSUE TITLE
[Story] Setup a Discord server for OpenChallenges

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2204]
### Description

- Review the server configuration of the NLP Sandbox Discord server
- Collect the specifications for OC Discord server
- Propose an architecture for OC Discord server

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Tentatively assigning @mdsage1

**Comment by mdsage1** [comment]
@tschaffter I just want to confirm that this:
- Review the server configuration of the NLP Sandbox Discord server

will operate independently from our OpenChallenges infrastructure, i.e. I do NOT need to build this in via our Dev container?

**Comment by mdsage1** [comment]
[ ] Created an [OpenChallenges server](https://discord.com/channels/1159949434671603782) from the template proved on NLP Sandbox Discord [server](https://github.com/nlpsandbox/discord)

**Comment by mdsage1** [comment]
@tschaffter What is meant by these:
- Collect the specifications for DREAM Discord server
- Propose an architecture for DREAM Discord server

Is this basically developing OpenChallenge specific channels?

**Comment by tschaffter** [comment]
I initially drafted the ticket to created a server for DREAM but let's create one for OC first. I updated the description of the ticket accordingly.

We can keep the "architecture" light for now with only a few channels (e.g. general, announcements). We also need a few roles, e.g. for admins, for members of the OC Team, and people who have accepted the Code of Conduct.

I accepted the invite and I'm now in the server. Thanks!

**Comment by mdsage1** [comment]
@tschaffter There are 5 channels that members can read and send messages. I've assigned roles for us and sent invitations to Verena and Rong.

**Comment by tschaffter** [comment]
Reopening because the Discord server is not fully configured yet (e.g. logo, rules)

**Comment by mdsage1** [comment]
@tschaffter 
I have the OpenChallenges logo in the Server Overview tab. I'm unsure where else I should have added it.
![image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/122999770/d61d8196-8034-4daf-9c86-766549f2bbae)

**Comment by mdsage1** [comment]
@tschaffter I thought that we were using the new Rules feature that came standard with Discord.

**Comment by tschaffter** [comment]
See below. The rules are also empty, could you please find a suitable set of rules that you think the participants to the server should abide? There are probably many templates available out there so we shouldn't need to write our own from scratch.

![image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/84074ae4-f42e-4058-839d-90720f52ceca)

**Comment by mdsage1** [comment]
Mentions of NLP sandbox have been replaced w/OpenChallenges in COMMUNITY/team, COMMUNITY/users, INFORMATION CHANNELS/rules, and INFORMATION CHANNELS/welcome.

**Comment by mdsage1** [comment]
Added the OpenChallenges logo to Discord.
![image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/122999770/89ea2fa3-46f4-4fcf-ad94-5b5a08dccd07)

**Comment by mdsage1** [comment]
The rules are updated and I have sent an invitation link to Gaia to become a member.

**Comment by mdsage1** [comment]
Added a new member requirement to send a message "Accept" in the rules channel.


![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/122999770/a53d0fc3-52a8-4662-846d-480a94a91577)
