### ISSUE TITLE
[Story] Explore the integration of EDAM ontology to OC

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2209]
### What product(s) is this story for?

OpenChallenges

### As a user, I want

As a Challenge Organizer, I want my challenges to be annotated with existing ontologies so that the annotations are useful to a wider group of users.

As an OC Developer, I want to leverage existing ontologies as much as possible so that we don't reinvent the wheel.

### Description

Explore how the [EDAM ontology](https://github.com/edamontology/edamontology) could be used to annotate challenge resources.

### Anything else?

I think that the first time the EDAM ontology was suggested in the context of OC was for assigning values about the input data type.

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by gaiaandreoletti** [comment]
- [X] EDAM ontology added to OC excel file

**Comment by tschaffter** [comment]
> EDAM ontology added to OC excel file

We should probably discuss what the integration would have looked like before updating the "production" spreadsheet. :slightly_smiling_face:

@gaiaandreoletti Can you please describe in this ticket what the solution you propose is?

**Comment by gaiaandreoletti** [comment]
To make it easier for me to search for the appropriate ontology based on the challenge data, I added the EDAM ontologies as a new column. However, we can decide to delete this column later on. Currently, the tab called 'input_data_types' contains the ontologies that correspond to the type of data found across all challenges listed in the excel file. Previously, this tab was empty. A drop down menu listing all ontologies was made created to facilitate process. iF the EDAM onthology for the type of data used in the challange was not available , I used either the topic or the operation reflecting the expetiment used. e.g.


Preotein function prediction	operation_1777 
Preoteomic experiment	topic_3520 
Pretein interaction data	data_0906 
Protein structure	data_1460 
Protein variants	topic_3120
RNA sequencing	topic_3170

**Comment by tschaffter** [comment]
I have never used EDAM personally but here are some questions:

- From the list you shared and from [EDAM README](https://github.com/edamontology/edamontology) page, I see that there are different concepts like `operation`, `format`, `data`. Are they all suitable to describe challenge input data type?
- Should the challenge input data type property take a single value or an array of values?
- Given the public information about a challenge, how would the protocol applied to identify the value(s) for the challenge input data type?

**Comment by tschaffter** [comment]
I think we have managed to narrow down how to annotate challenges with EDAM values!

Are we settling on what follows?

- Set input data type to an array of EDAM values (data, format and possibly topic ids)
  - Challenge may include multiple data type like, e.g. mammogram images and demographic information
- Add the property `challenge.operation` as a string that takes an EDAM operation id

@gaiaandreoletti @vpchung

**Comment by vpchung** [comment]
> Set input data type to an array of EDAM values (data, format and possibly topic ids)

By array, did you mean a comma-separated list...?  If so, I think it will be easier to follow the same table format as `contribution_role` where each row is a challenge_id and a edam_id (or edam_name).  For example:

id | challenge_id | edam_name
--|--|--
1 | 1 | Protein variants
2 | 2 | Systems biology
3 | 2 | Electronic health record

**Comment by vpchung** [comment]
> Add the property challenge.operation as a string that takes an EDAM operation id

There are only 3 challenges so far with an operation annotation, so this is done!  ✅

**Comment by tschaffter** [comment]
## Update

@gaiaandreoletti presented the EDAM ontology to the team and received positive feedback. The implementation is currently underway.
