### ISSUE TITLE
[Bug] Fix issues in OC Data sheet

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

OpenChallenges

### Current behavior

There are several issues in the OC Data sheet:

- There seems to be a "bug" that replaced the separator `-` by `:`. This affects several fields.
  - E.g. challenge name `Structure:free protein:ligand affinity prediction : Task 2 Fitting`
- Replace em dash by regular dash. E.g. `–` => `-`
- Do no include space before colon. E.g. `Hidden Treasures : Warm Up` => `Hidden Treasures: Warm Up`
- Use the default sheet font for all value. Some recent values uses the font Calibri or a Google font
- Do not use `_` as separator in slugs: E.g. `cmu_dnanexus_2023` => `cmu-dnanexus-2023`
- Do not use capital letters in slugs: E.g. `QBI-hackathon-2023` => `qbi-hackathon-2023`
- Do not surround description by double quotes or newline character: E.g. `"This fall, ..."` => `This fall, ...`
- Incorrect capitalization of constant values in fields like `incentives`, `submission_types`, etc.
- Invalid constant values in fields like `incentives`, `submission_types`, etc.

@vpchung @gaiaandreoletti 

### Anything else?

Related to #2064

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gaiaandreoletti** [comment]
@tschaffter  the following fields were corrected:

- [X] - replaced the separator : by - 
- [X] - Replaced em dash by regular dash. E.g. – => -
- [X] -  changed the inclusion of space before colon.
- [X] - Used the default sheet font for all value. Arial 10
- [X] -  used - as separator in slugs - fix bug specifically for Kaggle challenges
- [X] - Did not use capital letters in slugs
- [X] - Removed double quotes in description
- [X] - fixed Incorrect capitalization of constant values in fields like incentives, submission_types, etc.
- [X] - fixed constant values in fields like incentives, submission_types, etc.
in addition:
- [X] - added EDAM nomenclature under input_data_types
- [X] - as the SOP did not specify, added input_data which reflects  input_data_types EDAM onthology

**Comment by vpchung** [comment]
I think this is safe to close now?

**Comment by tschaffter** [comment]
@vpchung Go ahead and close the issue if the spreadsheet looks good to you.

**Comment by vpchung** [comment]
Some formatting changes needed to be reverted, but other than that, everything looks good on my end!

Closing now.
