### ISSUE TITLE
[Task] Add missing logos for "newer" organizations

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#2235]
"Newly" added organizations do not have their logos uploaded in our S3 bucket:

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/e7fd8da9-3bd6-46ef-bc0f-f20039c692b7)

This is mostly due to X no longer allowing non-users to access profiles, which was my main source of getting hi-def logos.

**Comment by vpchung** [comment]
CC: @gaiaandreoletti for transparency

**Comment by tschaffter** [comment]
Added tentatively to Sprint 23.11
