### ISSUE TITLE
[Task] Add temporal information to the challenge card ⭐

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#2240]
Update the challenge card, so that a user can more easily infer what the start/end dates are at a glance. For example:

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/7ee8f2dc-793a-442e-9b8a-1c4fa1544a5a)

See #2185 for more details.

**Comment by tschaffter** [comment]
Added to Sprint 23.11
