### ISSUE TITLE
[Task] Update OC code ownership to include Gaia

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2247]
### What product(s) is this story for?

OpenChallenges

### Description

List of files that Gaia should be invited to review:

- Project `openchallenges-api-description`
- SQL and CSV data files

@vpchung Anything else comes to mind?

### Tasks

- [ ] Update [`CODEOWNERS`](https://github.com/Sage-Bionetworks/sage-monorepo/blob/884bce418d23fd79aab83729f5b4b7a7e4eb9c05/.github/CODEOWNERS) files

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by vpchung** [comment]
> * Project openchallenges-api-description
> * SQL and CSV data files

These look good 👍🏼

**Comment by tschaffter** [comment]
Added to Sprint 23.11
