### ISSUE TITLE
[Story] Add EDAM annotations (data and full-text search)

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#2256]
Following up on #2209, add EDAM annotations curated by @gaiaandreoletti to the OC db.

Tasks:

- [x] #2520
- [x] Add a simplified version of EDAM to OC DB
- [x] Add the property `Challenge.operation` to OC API model (EDAM term)
- [x] #2551

**Comment by tschaffter** [comment]
Added to Sprint 10.11

**Comment by tschaffter** [comment]
Actually I'm sending that one back to Backlog. We need to better validate the existing data (#2064) before we can add more properties to the data mode.

**Comment by tschaffter** [comment]
## Update 2024-03-04

The API property `Challenge.operation` is now described with EDAM Operation. We have one more task about representing challenge input data type with EDAM before be can close this story.

**Comment by tschaffter** [comment]
This task is done. There is a pending task tracked by @gaiaandreoletti that consist in making sure that only "Data" concepts are used for the challenge input data types. The existing implementation supports this decision.

@gaiaandreoletti We are welcome to revisit this decision any time, e.g. if you want to start using ["Format" or "Topic" concepts](https://edamontology.org/page) to annotate the input data types of challenges.

**Comment by gaiaandreoletti** [comment]
only data concepts of edam were added to the challenge format
