### ISSUE TITLE
[Bug] Incorrect org name searched

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/sage-monorepo#2275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

OpenChallenges

### Current behavior

This org appears in very first search results of organization dropdown filter. It seems it displays the member information , other than the name of organization.

<img width="452" alt="Screen Shot 2023-10-25 at 7 47 16 PM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/73901500/28a09ca5-4271-4736-b803-3a0b2afa611f">

### Expected behavior

Display the name of organization.

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vpchung** [comment]
Thanks for the catch, @rrchai ! 

Looks like the [organizations sheet](https://docs.google.com/spreadsheets/d/1XRSUVqbZk_k9_rV1vpgPVMQ0fVV0mavwY8Aqyy0C2HQ/edit#gid=1828426045) was listing member information for some of the rows.  These rows have been updated to list the organization info only.

CC: @gaiaandreoletti
