### ISSUE TITLE
[Task] Add Sage Bionetworks logo to the footer ⭐

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2301]
### What product(s) is this story for?

OpenChallenges

### Description

Luca has requested that we make Sage contribution more visible. We have already taken steps towards this. The goal of this PR is to finalize this work.

Before:

- Sage logo was featured at the bottom of the Home page in the section "OC is made possible by...".

Current state:

- Luca shared that we should make the distinction being Sage is the author and ITCR is a sponsor.
  - We added Sage logo at the top of the Team page + added a Sage-related headline
  - We have removed Sage logo from the section "OC is made possible by...".
- Luca suggested to add the logo to the nav bar. However, a few team members expressed that this was a bit too much. The nav bar is also not a standard place to advertise anything else than the product itself.
  - The free space we had in the nav bar is now being used by other component (Discord button, API Docs, etc.)
- TODO: Discuss how we could add Sage logo to the footer so that it appears on all pages.

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
## Update

- Remove `Code licensed under Apache License 2.0` from the footer
- Remove `Documentation licensed under CC-BY 4.0`
- Add the Sage logo to the right side of the footer

**Comment by vpchung** [comment]
## Option 1a: colored logo on right-hand side
![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/4ba1daf3-be93-4209-a858-879ddb32d87c)


## Option 1b: all-white logo on right-hand side
![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/de97c786-3529-4be8-b8eb-b8f7ded10c3e)


## Option 2a: colored logo on right-hand side with the text, "Powered by"
![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/32c9a94b-0fa9-4803-8002-70b5ba156c06)

Mobile version:

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/70578338-beb8-4571-a061-dc6acf1d5aa1)




## Option 2b: all-white logo on right-hand side with the text, "Powered by"
![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/aae5bbb0-a6d8-4f07-a54a-c94cb4f415cc)

## Option 3: all-white logo on bottom, replacing "Sage Bionetworks" with logo

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/d71c33bb-f3df-48a4-9fa6-c2e381e94b5f)

Mobile version:

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/c8b102d8-b785-4b99-a144-f834464a964e)

**Comment by tschaffter** [comment]
Could you try the following: display the Sage logo on top of the app version and give it a size similar (height?) to the OC logo.

**Comment by vpchung** [comment]
Sure. Here we go:


![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/6ffc3d4d-45fa-49ec-845a-1c779bfc9ac6)


Mobile version:

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/2dd9cafd-3362-4a4e-a868-4b2678df891c)

**Comment by tschaffter** [comment]
LGTM!
