### ISSUE TITLE
[Bug] Fix website links of CAGI challenges

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

OpenChallenges

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gaiaandreoletti** [comment]
@tschaffter the links on the Excel files are fully functional - is something broken when importing it maybe?
cc @vpchung @rrchai

**Comment by tschaffter** [comment]
The OC Data includes this link `https://genomeinterpretation.org/CAGI4-pgp.html`, which is not functional.

**Comment by gaiaandreoletti** [comment]
@tschaffter  but this is functional: https://genomeinterpretation.org/cagi4-pgp.html
the upper case is screwing up the link @vpchung was this a format issue?

**Comment by vpchung** [comment]
Ah yeah, looking back at our history, the change of the URLs were introduced in [`7e53420`](https://github.com/Sage-Bionetworks/sage-monorepo/commit/7e53420e26e751fd97cc68d3f59fd2b6a946db16).  I can go through and lowercase "CAGI" in those links.

**Comment by tschaffter** [comment]
Done
