### ISSUE TITLE
[Task] Update the challenge card to display the entire headline

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2320]
### What product(s) is this story for?

OpenChallenges

### As a user, I want

NA

### Description

The currently AI-generated headlines should have ten words or less. Depending on the number of characters in the headlines, it may not be entirely visible as in the example shown below.

The goal of the ticket is to increase the space for headlines from 2 to 3 lines on the challenge cards. If this is still not enough for a headline to be fully visible, the headline should be modified. Meanwhile, keeping the code that truncate headlines and adds "..." should be kept.

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
I tried to set in `_general.scss`:

```scss
.mat-caption {
  @include line-clamp(3);
}
```

but the headlines are still truncated. I know remember that the headlines are truncated when data are exported from the OC spreasheet.

**Comment by vpchung** [comment]
Spreadsheet has been updated to include data validation on the headline (120 characters or less).  For the currently existing headlines that are longer than this limit, should they be removed?

**Comment by tschaffter** [comment]
Sounds like a plan!

**Comment by vpchung** [comment]
After looking at the proposed design, we have decided to stick with 80 characters as the max limit.

Can this ticket be closed? @tschaffter
