### ISSUE TITLE
[Task] Always show information about End date for active challenges

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2325]
### What product(s) is this story for?

OpenChallenges

### As a user, I want

As a User, I want to know when an active challenge ends so that I can factor this information in when deciding whether I want to participate.

### Description

There are active challenge cards that do not show information about the End date. From a User perspective, it's unclear what the reason could be.

<img width="1086" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/34472e0b-bed8-48ec-9e21-658f6d3b210d">

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
This suggestion applies to upcoming challenges too where information about the Start date would be expected. Here User may expect that no start date has been specified so it may be OK to not show anything, which sounds better than showing "No start date specified". Otherwise, information about the start date should be shown independently of how far away it is.

**Comment by vpchung** [comment]
Some challenges, e.g. challenges hosted on Eterna, do not list when their end dates are, hence why there are no timeline indications.  imo, leaving the cards as-is seems fine, but if showing some information is required, we could either add:

"No information about end date available"

or 

"No end date found"

**Comment by tschaffter** [comment]
That make sense when the date is not available (start date for upcoming challenges or end date for active challenges).

Is the date information also hidden when the date is far away? For do we show "Ends in 6 months" or do we hide this information because we would consider it "far away"?

**Comment by vpchung** [comment]
For active and upcoming challenges, we do not hide the timeline information, as I thought they would be valuable in these cases.  I mentioned the use case [here](https://github.com/Sage-Bionetworks/sage-monorepo/pull/2315) as well.

**Comment by tschaffter** [comment]
The current implementation is the one we need. Nothing to do.
