### ISSUE TITLE
[Task] Add cameo3d challenges to OC

### ISSUE THREAD

**Issue by juwrgenhaas** [Sage-Bionetworks/sage-monorepo#2334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

Other

### Current behavior

Cameo3d.org is not listed. It is a continuous challenge with a weekly recurrence. 

### Expected behavior

List automated challenges as well

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gaiaandreoletti** [comment]
added them!

**Comment by tschaffter** [comment]
@gaiaandreoletti Can you please add an update to this ticket?

**Comment by gaiamarea** [comment]
Updated 2023-11-13

**Comment by gaiaandreoletti** [comment]
Updated 2023-11-13

Challenge added

**Comment by tschaffter** [comment]
I see the challenges in production. Closing.
