### ISSUE TITLE
[Bug] Revisit the Not Found page in OC

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

OpenChallenges

### Current behavior

The content of the 404 page is partially masked by the navbar.

![image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/03e29c9b-c6cb-453a-8991-a4ff62efd32f)

### Expected behavior

The content is not cropped.

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vpchung** [comment]
@tschaffter when do you observe this? Is it on the MBP screen? On my end, I only see this if I make the window super short:

![Screenshot 2023-11-09 at 12 40 25 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/1e725845-0083-41c1-a73b-edc0575b9658)

![Screenshot 2023-11-09 at 12 40 35 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/9a16f834-5e7f-465c-b54f-4a947ee0941c)

**Comment by tschaffter** [comment]
> when do you observe this?

On my MBP 13 inches. It's like the footer is stuck while it should be the case only if there is not enough content in the main container.

**Comment by tschaffter** [comment]
Maybe by setting a min height to a container that includes page content and configure it so that it does not overlap with the navbar?

**Comment by vpchung** [comment]
On my MBP 13 inches, my screen looks like this:

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/467a09af-e6bb-41a5-a9a5-8c3b101b2f05)

Not quite as cut-off as yours, but I can revisit it anyway.

**Comment by vpchung** [comment]
> [set] a min height to a container that includes page content and configure it so that it does not overlap with the navbar?

I believe this is already accounted for in our theme:

```
html {
  margin-top: constants.$navbar-height;
}
...
.base {
  width: 100%;
  min-height: calc(100vh - constants.$navbar-height - constants.$footer-height);
}
```

🤔 hmm..

**Comment by tschaffter** [comment]
The 404 container may overlap with the navbar (see below)

<img width="1440" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/c8d70cea-29fa-4a38-80d3-f4aa79ceac83">
