### ISSUE TITLE
[Bug] Missing submission type should show "Not available"

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

OpenChallenges

### Current behavior

The challenge "Foot Ulcer Segmentation Challenge" shows:

<img width="359" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/30aa7662-1055-4995-bcf1-e942c51c5252">

### Expected behavior

The challenge "Foot Ulcer Segmentation Challenge" shows a blank field for the submission type. It should show "Not available" or "other".

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vpchung** [comment]
Thanks for the catch! 

For some reason, I didn't add the same logic to `submissionTypes` when I handled `inputDataTypes` and `incentives`....
