### ISSUE TITLE
[Bug] Getting OC CAGI logo return 404 error

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

OpenChallenges

### Current behavior

```console
2023-11-18 02:57:47 tornado.access:WARNING 404 GET /Vgl6inm5i-XIx6E4aypBEoaeX0U=/140x140/logo/CAGI.png (172.27.0.1) 214.64ms
```

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vpchung** [comment]
Ah, nice catch!  I just checked the Google Sheets - not sure when, but its objectKey was updated without my knowledge.  I just checked our S3 bucket and the objectKey should be `cagi.png`, not `CAGI.png`.

Will fix push the latest fix on Monday.
