### ISSUE TITLE
[Story] Optimize the OC home page for mobile

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2378]
### What product(s) is this story for?

OpenChallenges

### As a user, I want

As a New User, I want OC home page to present well on my mobile device, so that I can focus on the page content.

### Description

The home page is one of the two most used landing pages along with the challenge search page. Also, most new users are on a mobile when they visit OC. for the first time.

The goal of this ticket is to start with optimizing the OC home page for mobile devices. The page currently looks OK but the layout and styles could be improved in terms of responsiveness.

Cc: @vpchung 

### Acceptance criteria

- All the sections of the home page have been reviewed
- The ticket includes a list of changes that we could implement to make the home page more responsive
- The changes are implemented in one or multiple PRs.

Out of scope:
- Pages that are not the home page

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Added to Backlog

**Comment by tschaffter** [comment]
Added to Sprint 23.12

**Comment by tschaffter** [comment]
Resolution: 390x844 most popular mobile resolution

![image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/326edc19-80b5-437d-abcc-4755368b633f)

**Comment by tschaffter** [comment]
Added to Sprint 24.1

**Comment by tschaffter** [comment]
@vpchung Can you please share an update?

**Comment by tschaffter** [comment]
Added to Sprint 24.2

**Comment by vpchung** [comment]
A PR has been opened for this: #2483
