### ISSUE TITLE
[Task] Test that the paginator behave as expected on the challenge search page (e2e)

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2380]
### What product(s) is this story for?

OpenChallenges

### As a user, I want

As a developer, I want to develop e2e tests for the components of the OC web app, so that unexpected behaviors that originate from code changes are automatically detected.

### Description

The goal of this PR is to explore the development of e2e tests for the OC web app with Playwright with a concrete objective: assert that the paginator on the challenge search page behave as expected in various situations.

Example:

1. Go to the challenge search page
2. Go to the second page
3. Make a change to the challenge query input

=> Assert that the paginator page number has been reset to 1.

See `apps/openchallenges/app/e2e/challenge-search-paginator.spec.ts`.

### Acceptance criteria

TODO

### Anything else?

Start by reviewing #2379 for an intro to e2e testing of the OC web app with Playwright.

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
@rrchai Can you please add an update to this ticket?

**Comment by tschaffter** [comment]
Moved to Sprint 24.01

**Comment by tschaffter** [comment]
Added to Sprint 24.02

**Comment by tschaffter** [comment]
As per our discussion, @rrchai will add the e2e test this week.

**Comment by rrchai** [comment]
New due day: Feb 20th.

**Comment by tschaffter** [comment]
## Update 2024-02-22

This task has been delayed once again. New due date needs to be clarified with Jake and Rong.

**Comment by rrchai** [comment]
## Update
@rrchai  will be back working on this pr later this week.
