### ISSUE TITLE
[Bug] Set the platform to `NULL` for challenge that don't use a registered platform

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

OpenChallenges

### Current behavior

The OC Data sheet registers a platform named "other". A first issue is that counting the platforms from the list of challenge platform returns currently 14 while we technically capture information only about 13 platforms. Other issues may arise as we plan to create a challenge platform search page.

Instead, we should no longer create a platform for "other" and set the property `challenge.platform` to null / undefined when no known challenge platform is used by the challenge. This approach implies changes at the following levels:

1. [x] OC Data sheet (@vpchung )
2. [x] OC data model (SQL) (@vpchung )
3. [x] OC API model (`openchallenges-api-description`) (@rrchai )
4. [ ] Challenge service (@tschaffter )
5. [ ] Web app (@rrchai )

The above tasks should be performed in this order, and this will be reflected on the person assigned to this ticket. Let's try to do everything in a single feature PR that Verena will create as the first contributor to keep thing simple.

Cc: @vpchung @rrchai 

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vpchung** [comment]
PR started in #2393.

🏀  passing it to you now, @rrchai !

**Comment by tschaffter** [comment]
Working on updating the API description so that it works well with code generation

A challenge without known platform is 67 (for testing).

**Comment by tschaffter** [comment]
An DTO object freshly created comes with falsy values:

```
challenge dto initial: class ChallengeDto {
    id: null
    slug: null
    name: null
    headline: null
    description: null
    doi: null
    status: null
    difficulty: null
    platform: null
    websiteUrl: null
    avatarUrl: null
    incentives: []
    submissionTypes: []
    inputDataTypes: null
    startDate: null
    endDate: null
    starredCount: 0
    createdAt: null
    updatedAt: null
}
```

**Comment by tschaffter** [comment]
## `nullable` is replaced by `null` type in OpenAPI 3.1

> **Note**
> we are still using OpenAPI 3.0.3

See https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0
