### ISSUE TITLE
[Feat] Create documentation site

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#2395]
Currently, all of our docs are accessible from the repo only.  It would be nice if we could host a "pretty" view of the docs as well.

I plan to follow the [Diátaxis](https://diataxis.fr/) structure when porting over the docs.

**Comment by tschaffter** [comment]
I configured Pages from the settings tab. There is still no ling to Pages on the main page of the repo.

<img width="801" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/a1c71716-d93e-4502-8878-7a5a7eeffa94">

**Comment by tschaffter** [comment]
Reopening until we can access the Pages

**Comment by tschaffter** [comment]
Here are the [logs](https://github.com/Sage-Bionetworks/sage-monorepo/actions/runs/7217465154/job/19665330401) of the error during the build step.

**Comment by tschaffter** [comment]
The [docs site](https://sage-bionetworks.github.io/sage-monorepo/) is live!
