### ISSUE TITLE
[Bug] Developing inside a Container and other docs pages are broken

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

Sage Monorepo

### Current behavior

[Developing inside a Container](https://sage-bionetworks.github.io/sage-monorepo/docs/devcontainer.md)

![image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/b7e6a260-a269-4e72-bed5-307e64944d20)

### Commit ID

dad64404889de9d7f5f7caa7fe2b2692aa092c72

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vpchung** [comment]
Before addressing this bug, I think it'll be best if we first revisit, as a team, which docs/pages will be essential to the docs site.

**Comment by tschaffter** [comment]
@vpchung What about decoupling the solution for rending docs pages (this ticket) from future work required to update the content of the docs?

**Comment by tschaffter** [comment]
The issue has been clarified with @vpchung. See her comment above. This work will be captured in a separate ticket.
