### ISSUE TITLE
[Bug] OC says that a challenge ends in 4 days, but it has added 4 days ago

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

OpenChallenges

### Current behavior

Consider this [challenge](https://openchallenges.io/challenge/481/ntx-hackathon-2023-sleep-states?tab=overview).

The card shows that the challenge is `active` ends in 4 days.

<img width="334" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/788f2c95-66ad-4e0a-a168-2afae9ef54b9">

but the end date is "2023-12-15" (4 days ago).

### Expected behavior

The challenge should be marked as complete and it should says that it has completed 4 days ago.

### Anything else?

- The status is out of date because it has changed since the last time the OC Data sheet was exported (more than 4 days ago).
- One of the priorities of 2024 will be to update the status more frequently, e.g. using a scheduled job to update the status in the DB based on rules and start/end date.
- The label "ends in 4 days" is probably because of a bug that should be fixed as part of this ticket.

Cc: @rrchai 

### Commit ID

dad64404889de9d7f5f7caa7fe2b2692aa092c72

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
@vpchung The proposed solution does not prevent the issue from happening again.

@rrchai @vpchung What are the solutions that you can think of that could solve this issue once for all?

**Comment by tschaffter** [comment]
Moved to Sprint 24.01

**Comment by rrchai** [comment]
As we curate the DB and update the status of challenges weekly, there could be a 7-day window that exposes opportunities for mismatches (the actual dates & status shown on challenge card & time info "Started ... ago" etc.), which could potentially impact the user experience. Suggested proposals:

### Proposal 1

- We still manually update the challenge in DB weekly 
- Add dynamic validation to check if 'upcoming' challenges become 'active', and if 'active' challenges become 'completed'.
- Display the most updated status.

### Proposal 2

1. Let challenge have two properties related to its status.
    - `status`: dynamic status, automatically changed via `startDate` & `endDate` only on the backend (this can be temporarily done on the frontend as well - #2448).
    - `isCompleted`:  boolean whether the challenge is completed or not (current completed challenges can be set with `true` for this property)
2. Future: only developers can alter `isCompleted` - can choose a date (>=Now) or leave blank for endDate.
3. Future: proposed start/end dates are required properties if not yet and organizers are responsible to update dates to reflect status.

---
I could also quickly do proposal 1 to solve the issues for any future potential mismatches (only 1 as of 1-24-2024).
---
Some stats with current challenges data:
- challenges outdated: 1 ("Frost Hacks")
- challenges without both dates: 117
- challenges with start date, but no end date: 56 
- challenges with end date, but no start date: 58

**Comment by tschaffter** [comment]
After giving this issue more though, I think the best strategy is to update the frequency of the data to daily.

@vpchung Could you create a CI workflow that update the OC data once a day?

**Comment by tschaffter** [comment]
Thanks @rrchai for the suggested solution. As per our discussion, we will increase the frequency of the data updates. @vpchung is currently working the GH workflow that will automate the transformation from Google sheet to CSV.

**Comment by tschaffter** [comment]
Added to Sprint 24.2
