### ISSUE TITLE
[Story] Make the list of platforms on home page mobile friendly

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2427]
### What product(s) is this story for?

OpenChallenges

### Description

- Enable user to click on each logo to be redirected to the platform site
- Make the layout mobile friendly (1 log per line?)

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
This ticket is related to #2378 but will be implemented in a separate PR.

**Comment by tschaffter** [comment]
Example of fitting all logos within the same shape (MLCommons)

<img width="1552" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/60ec026c-3462-41e6-84b4-77696ae840c9">

**Comment by tschaffter** [comment]
@vpchung Can you please share an update?

**Comment by tschaffter** [comment]
Added to Sprint 24.2

**Comment by vpchung** [comment]
I have not had time to work on this Story in 24.1 or 24.2 - will try to work on it in 24.3.

**Comment by tschaffter** [comment]
The logos actually render nicely on the latest Home page.

On Galaxy Note 20:

![Screen Shot 2024-03-04 at 11 15 59](https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/a6a8834f-a1df-4f07-b53a-b5c0f258393c)

On iPhone 12/13:

![image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/6f1c7205-213d-454a-b863-d85675e7193a)

@vpchung Do you agree that the platform logos now look nice enough for now?

**Comment by vpchung** [comment]
LGTM, but it lacks the ability to go to the platform page, which is also an ask for this Story, right?

**Comment by tschaffter** [comment]
Let's redirect the user to the platform search page once we have it.

Closing this ticket now as the main goals of this ticket are met.
