### ISSUE TITLE
[Task] Add Biomarkers of Aging Challenge to OC

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2467]
### What product(s) is this story for?

OpenChallenges

### Description

Add [Biomarkers of Aging Challenge](https://www.synapse.org/#!Synapse:syn52966292/wiki/624696) to OC. This is a request from Luca.

Luca suggested that this challenge should be returned for the keyword "bioage" based on the link he shared below:
https://openchallenges.io/challenge?searchTerms=bioage

We currently don't support keywords, so the term "bioage" should be added to the challenge description for OC to pick it up.

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by vpchung** [comment]
Done.
