### ISSUE TITLE
[Bug] The plot of the OC home page is out of sync

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

OpenChallenges

### Current behavior

Until recently, we updated the OC data files (CSV) manually. This also applied to the data of the plot on the OC home page that were updated manually too.

We are now using a GH workflow to update the CSV files but not the plot data. As a result, the plot data may become out of sync with the content of the DB.

### Expected behavior

The plot reflects the content of the OC DB.

### Anything else?

Task:

- [ ] Update the OC challenge service to automatically generate the plot data instead of relying on static values.

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vpchung** [comment]
A temporary fix has been merged for this bug (#2504) but I'm leaving this ticket open as it has been discussed (over Slack) that a more robust solution is desired.

**Comment by tschaffter** [comment]
Added to Backlog

**Comment by tschaffter** [comment]
We will continue to rely on the temporary fix for now.
