### ISSUE TITLE
[Feature] Allow devs to publish docker images from feature branches

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/sage-monorepo#2552]
### What product(s) is this feature for?

Schematic

### Description

Currently, `build-devcontainer-image.yml` only gets triggered when there is a push to main. Please update it so that docker images can be published from local branch. For example, in schematic, workflow can be triggered by tags (see workflow [here](https://github.com/Sage-Bionetworks/schematic/blob/develop/.github/workflows/docker_build.yml)) in certain formats. 

This will allow devs to test new features/bug fixes before merging to main. Since schematic API needs to be run in a docker container, this will also allow us to make sure that schematic APIs are working before each deployment. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
Thanks for opening this ticket and sharing workflow used by Schematic.

Is another way to phrase the problem that you want to publish image during the development of a feature, e.g. triggered by pushing a commit to the PR, for the sake of testing the image before merging the feature?

Could these tests be implemented as integration tests that are run by the CI workflow in a way that there wouldn't be a need to publish the image to a registry?

**Comment by tschaffter** [comment]
@linglp It's now possible to tag all the images of a product (e.g. Schematic) with a non-moving, semver tag when creating a GitHub tag. You can see an example of image tagged here: https://github.com/Sage-Bionetworks/sage-monorepo/pkgs/container/openchallenges-apex

This feature is enabled for OC and Agora. I can enable it for Schematic upon request. I'll further advertise this feature to the Schematic team next week.
