### ISSUE TITLE
[Feature] Create a filter component for challenge input data types

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2578]
### What product(s) is this feature for?

OpenChallenges

### Description

- Enable the user to visualize all the input data types that exist
- Enable to configure the filter so that only the input data types that are associated to at least one challenge are visible
- Enable the user to type keywords in an input field to filter further input data types
- The filter component/service generates an array of data types ID (e.g. EDAM concept class id) that can later be used to filter challenges

To discuss: how could we represent the hierarchical relationship between different data types since EDAM support this? Identify the pros and cons (potentially more difficult to implement; less user-friendly?)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
The first version of the filter could be a list of checkboxes with a input field to filter the concepts. This would be the same implementation as the one we implemented previously and then removed to make room for the EDAM concepts.

1. Create endpoint to search EDAM concept (#2608)
2. Create the UI component (this ticket)

**Comment by rrchai** [comment]
@tschaffter It seems the EDAM data concepts fit more into the "Input Data Type" category. Is the operation also part of the "Input Data Type" filter?

**Comment by tschaffter** [comment]
For now we are only using "Data" concepts as values for the [input data types](https://github.com/Sage-Bionetworks/sage-monorepo/blob/ad72df88ee32b9200b6b5583c2214c6ff8664484/libs/openchallenges/api-description/src/components/schemas/Challenge.yaml#L32-L35).
