### ISSUE TITLE
[Bug] Fix MLCube casing typo

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

OpenChallenges

### Current behavior

The official casing is MLCube but is displayed as "Mlcube" on the challenge page. The casing is different on the challenge page:

See the challenge page for one of those: https://openchallenges.io/challenge?submissionTypes=mlcube

I fixed the casing last week for the filter. Ideally, we should define the mapping from the constant to human-friendly name once and then use it for the filter and the challenge page.

> Submission Type	Prediction file, Mlcube

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rrchai** [comment]
Add a mapping file for MLCube in `challenge-overview` component
- key: slug, value: label
