### ISSUE TITLE
[Task] Update Gaia's profile on the OC Team page

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2609]
### What product(s) is this story for?

OpenChallenges

### Description

@gaiaandreoletti has accepted the role of OC Data Lead. The goal of this task is to reflect this change to the Team page.

- Place Gaia in second position after me
- Update Gaia's title to "Data Lead"
- Update Thomas' title to "Team Lead"
- Capitalize the other titles

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by vpchung** [comment]
This should be trivial to complete - will try to do so in the May sprint.

**Comment by tschaffter** [comment]
Added to Sprint 24.5
