### ISSUE TITLE
[Feature] Extend EDAM endpoint with sorting capabilities

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/sage-monorepo#2642]
### What product(s) is this feature for?

OpenChallenges

### Description

Enable to allow EDAM results to be sorted alphabetically and by relevance, and/or by other sorting types as needed.

~~By default, the EDAM results should be listed alphabetically. When a user applies a search term to filter the EDAM results, the results should be sorted by relevance.~~
By default, the EDAM results should be sorted by relevance.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
We can reuse the implementation that we use for challenges. Is it OK to keep the default sorting by relevance at the backend level and then at the client level you specify the sorting strategy you want to apply?

**Comment by rrchai** [comment]
> Is it OK to keep the default sorting by relevance at the backend level and then at the client level you specify the sorting strategy you want to apply?

Yes, this is correct. I have updated the description to sort results by relevance as the default in the backend.

**Comment by tschaffter** [comment]
@rrchai Actually, the sorting strategy by relevance applies a sorting by preferred label if the search terms specified are empty. This is different from what I've said before and should simplify the code in the web app.
