### ISSUE TITLE
[Bug] Remove duplicated challenge slug "chaimeleon"

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

OpenChallenges

### Current behavior

There are two challenges in `main` that have the same challenge slug: challenges with IDs 183 and 519.

https://github.com/Sage-Bionetworks/sage-monorepo/blob/main/apps/openchallenges/challenge-service/src/main/resources/db/challenges.csv

Tasks:

- Fix the duplication
- Review why the process allowed a duplicated challenge slug while they should be unique

### Expected behavior

Upon starting, the challenge service should not thrown this warning reported by @zaro0508 :

```
2024-07-15 21:27:07 WARN  [main] o.f.c.i.s.DefaultSqlScriptExecutor - DB: Duplicate entry 'chaimeleon' for key 'slug' (SQL State: 23000 - Error Code: 1062)
```

### Commit ID

04dc1bb81f9ebe06706dca1e56b1ff4026666f04

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vpchung** [comment]
Thanks for catching this, @tschaffter !  There was a small bug in the validation formula so it wasn't caught.  I have since fixed the formula, as well as updated the data so that there is no duplicate.
