### ISSUE TITLE
[Bug] Full-text search for platforms and orgs does not work on the challenge search page

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

OpenChallenges

### Current behavior

Using the full-text search to filter the results in the platforms and organizations filters do not affect the content of the platforms and orgs list.

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
@rrchai I confirm that the backend is working fine.

- https://openchallenges.io/api/v1/challengePlatforms?searchTerms=synapse
- https://openchallenges.io/api/v1/organizations?searchTerms=sage

**Comment by tschaffter** [comment]
The UI component to filter challenges by input data types, which also includes a full-text search field, works fine.

**Comment by rrchai** [comment]
I can confirm that the issue is not caused by the outdated version of primeng. I will look into the front-end logic to trace the bug.
