### ISSUE TITLE
Set max line length to 100 characters

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#386]
- We are currently using 80 chars (read more about this [old standard](https://en.wikipedia.org/wiki/Characters_per_line)).
- A longer max line length would
  - reduce the number of line in files.
  - as this project promote the use of descriptive variable/function names, such names are longer than "old" variables names used decades ago like "a =" and thus wide lines would be appreciated.
- In recent years, companies like Google have increased their max line line, e.g. to 100 for Google.

I propose to increase the max line length to 100. This change would need to be applied at several places:

- VS Code extension `rewrapped`.
- TypeScript / HTML / Java / Python linters.

I would recommend to open one PR per type of files instead of updating everything at once and then having a long PR that may break or be too long to easily review.

## Tasks

- [x] #418
- [x] #420
- [x] #460

**Comment by tschaffter** [comment]
@rrchai @vpchung What do you think? This change would be applied later this year, so we have time for a lengthy debate if needed. ;-)

**Comment by vpchung** [comment]
I like the idea of increasing the max line length, especially since screens are massive now :-)

**Comment by vpchung** [comment]
Should comments also have a max line length of 100?  e.g. for Python, comments and docstrings are encouraged to be 72 characters or less.
