### ISSUE TITLE
Review Agora and integrate to the evalutation of CP dev strategies

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#475]
Agora is developed in TypeScript-Angular.

https://github.com/Sage-Bionetworks/Agora

Notes:

- Review the integration between Agora and Synapse.
- Review code for ideas to reuse in the CR.
- Review list of Agora team members.

**Comment by thomasyu888** [comment]
I'd be curious to know more about how the data is actually linked as well. As far as I know, we run an ETL pipeline and update some files on synapse.

I can learn more from Jess B.
