### ISSUE TITLE
Create a pipe to transform camel case to space separated work

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/sage-monorepo#537]
put in the `libs/shared/util`

**Comment by tschaffter** [comment]
@rrchai Is this task still needed?

**Comment by rrchai** [comment]
@tschaffter Yes, it is used for schemas that used camel case, but need to split by space in UI, i.e: separate "GoodForBeginners" into "Good For Beginners" for challenge difficulty level. It's a good-to-have feature/util, but not urgent.

**Comment by tschaffter** [comment]
Thanks for the update. I'm assigning this ticket to you and placing it in the Backlog.

**Comment by tschaffter** [comment]
Will reopen when needed
