### ISSUE TITLE
Explore migrating to zsh along with OhMyZsh & zsh-autosuggestions plugin

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#589]
We are currently using the bash shell in the dev container in part because that's what I've been using for years. I would like to revisit whether this is the most convenient solution for most members of the team.

@rrchai I kind of remember that you are using zsh, which I think is now the default on macOS. Is that correct? Are there features of `zsh` that you are missing when developing with a `bash` shell?

@vpchung Do you have any preference between `bash` and `zsh`?

**Comment by vpchung** [comment]
Yep, `zsh` is the default now for macOS (which you can reset to `bash` if desired).

AFAIK, `zsh` has plugin and theme support, and can also attempt at fixing mistakes in typing directory paths.  That being said, I didn't see a huge difference between the two, so I always just stuck with `bash`.  I'm good with whatever.

**Comment by tschaffter** [comment]
Not needed for now
