### ISSUE TITLE
Set path alias for scss files

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/sage-monorepo#627]
The path alias of typescripts can be set in the `tsconfig.base.json` file, but it will not respect for styles/scss files.  Find a solution to set path alias for styles as well, i.e `@use '@sagebionetworks/challenge-registry/styles/src/lib/colors'`.

**Comment by tschaffter** [comment]
[This thread](https://github.com/nrwl/nx/issues/3203#issuecomment-997386909) is referring to what we would like to do. The task is related to how Nx organizes project so the keyword "nx" should be included in Google searches.

**Comment by tschaffter** [comment]
We are moving away from the current styling solution. We are currently exploring Tailwind.
