### ISSUE TITLE
Upgrade the Challenge profile page to the ROCC Specification v3

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#684]
The goal of this Story is to upgrade the frontend and backend of the Challenge page to meet the ROCC Specification v3.

Definition of Done: The look and feel of the page and behavior as defined in Specification v3. No need to be live.

## ROCC Specifications

- v3
  - [UI v3 Specification](https://www.figma.com/file/yAeIrg6Whc8Bqj2EnG4MWP/Challenge-Registry)
- v2
  - Legacy code developed before we moved the project to this monorepo.

## Tasks

>**Note**
> Decompose this task in smaller tasks/PRs if possible.

- [x] #694

Depends on:

- #411

**Comment by tschaffter** [comment]
Added to Sprint 22.09

**Comment by tschaffter** [comment]
Today we discussed with @rrchai and identified two ways to start working on the challenge page:

- Export the Challenge page from TeleportHQ OR
- Create Challenge page from User Profile page (after fixing layout size)

We will go with Option 2 as this approach is recommended by @vpchung .

**Comment by tschaffter** [comment]
@rrchai Once opened PRs for the user profile are merged, you should be able to reuse the code for the challenge and organization page. Verena offered today to help with this task if needed.

**Comment by tschaffter** [comment]
## Sprint 22.09 review

The goal was to complete #316, then copy-paste the code to create the challenge page, which has the same/similar layout. This story will be completed in Sprint 22.10.

**Comment by tschaffter** [comment]
Added to Sprint 11.10

**Comment by tschaffter** [comment]
Following our last meeting and discussions, @rrchai aims to open a PR that add the challenge page when he's back from vacation. The completion of the challenge page including querying data from the challenge service could be achieved in sprint 22.12.

**Comment by rrchai** [comment]
> The completion of the challenge page including querying data from the challenge service could be achieved in sprint 22.12.

Should challenge page start querying real data instead of mock-up data?

**Comment by tschaffter** [comment]
@rrchai The goal is for me to finalize the user service mid-December so that we can get data from it.

**Comment by rrchai** [comment]
@tschaffter I think this ticket is about challenge page UI, which has been merged. We make this ticket dependent on the #411 was because we would like to copy-paste the styles code from user profile page (which was not ready at that time). It seems to me that this ticket is not involved with user service and could be closed?

**Comment by tschaffter** [comment]
We have a handful of tickets titled "Upgrade X page to UI v3 (read only)", which also include the tasks relative to getting data from the backend. Even if the title includes "UI", some changes may be required on the data schema / backend side to meet the requirements of the new UI.

**Comment by tschaffter** [comment]
@rrchai @vpchung I'm swapping this Story (full upgrade of Challenge page) by #685 (full upgrade of Organization page) for Sprint 22.12.

**Comment by vpchung** [comment]
Close ?
