### ISSUE TITLE
Upgrade the Organization page to ROCC Specification v3

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#685]
The goal of this Story is to upgrade the frontend and backend of the Organization page to meet the ROCC Specification v3.

## ROCC Specifications

- v3
  - [UI v3 Specification](https://www.figma.com/file/yAeIrg6Whc8Bqj2EnG4MWP/Challenge-Registry)
- v2
  - Legacy code developed before we moved the project to this monorepo.

## Tasks

- [x] #843
- [x] #841

## Depends On

- #411

**Comment by tschaffter** [comment]
Added to Sprint 22.09

**Comment by tschaffter** [comment]
@rrchai Once opened PRs for the user profile are merged, you should be able to reuse the code for the challenge and organization page. Verena offered today to help with this task if needed.

**Comment by tschaffter** [comment]
## Sprint 22.09 review

The goal was to complete #316, then copy-paste the code to create the organization page, which has the same/similar layout. This story will be completed in Sprint 22.10.

**Comment by tschaffter** [comment]
Added to Sprint 22.10

**Comment by tschaffter** [comment]
Keeping this story around because we still need to bring data from the backend, which I'm working on right now.

**Comment by vpchung** [comment]
Close?
