### ISSUE TITLE
Upgrade the Challenge Search page to the ROCC Specification v3

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#748]
The goal of this Story is to upgrade the frontend and backend of the Challenge Search page to meet the ROCC Specification v3.

## ROCC Specifications

- v3
  - [UI v3 Specification](https://www.figma.com/file/yAeIrg6Whc8Bqj2EnG4MWP/Challenge-Registry)
- v2
  - Legacy code developed before we moved the project to this monorepo.

## Tasks

- [x] Create placeholder page for the challenge search page
- [x] #937
- [x] #938
- [x] #939
- [x] #940 
- [x] #941
- [x] #942
- [x] #943
- [x] #1160
- [x] #1041
- [x] #1176
- [x] #1110 
- [x] #1111
- [ ] #1035
- [ ] #1132

**Comment by tschaffter** [comment]
Added to Sprint 22.10

**Comment by tschaffter** [comment]
Hopefully the work on the challenge search page can start this sprint. Following our last team discussion, the goal is to have the challenge search page implemented by the end of the year (sprint 22.12).

**Comment by tschaffter** [comment]
Added to Sprint 22.12

**Comment by tschaffter** [comment]
I reopened this Story because we only completed the first step.

**Comment by tschaffter** [comment]
@rrchai Let's break down this story into individual tasks. We should then address each of this task with a PR. Do you want to propose a list of task for this story (maybe one task per filter type)?

**Comment by rrchai** [comment]
@tschaffter Sure. In terms of UI, here are the list of tasks:
- Create the placeholder that has been completed via #884 

Filters (using mock-up data):
- Add date picker filter - challenge year
- Add checkbox filter - status, difficulty, submission type, input data type, incentive type, platform
- Add dropdown filter - organization, organizer
- Add sort filter - start/end date, featured, # of stars, # of participants, # of views, alphabetical
- Enable search feature
- Add pagination
- Add list-view challenge card - optional

**Comment by vpchung** [comment]
> Add list-view challenge card (as well as list/grid switch button) - optional

Something to consider before we put effort into the card vs list layouts: https://www.eleken.co/blog-posts/card-ui-examples-and-best-practices-for-product-owners#toc-2

Adam also didn't see a purpose for the view change, so we may want to further discuss this "feature".

**Comment by rrchai** [comment]
@vpchung Thanks for sharing. I agree to re-consider whether the list layouts is necessary nowadays, at least I don't use it often. Meanwhile, I am not sure if other users get used to using the feature (maybe quicker searching for simplified contents). I do see [kaggle](https://www.kaggle.com/competitions) still has this feature, but it doesn't mean it's necessary. 

Maybe we could hold this feature until it's requested? I put it as an optional feature anyways.

**Comment by tschaffter** [comment]
@rrchai Looks good! I'll open the tickets for these tasks shortly.

**Comment by tschaffter** [comment]
The remaining work is tracked in scoped ticket. Closing this big one.
