### ISSUE TITLE
Create onboarding document for challenge organizations

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#875]
The goal is to create a short onboarding document or a two-pager that we can share with organizations that we want to collaborate with before the release of the closed beta. Existing resources that we can use as example include the two-pager we created for IBM and the NLP Sandbox onboarding document.

**Comment by tschaffter** [comment]
Targeting to have this document by the end of the sprint 22.12 so that we can start onboarding organizations early 2023.

**Comment by tschaffter** [comment]
[ROCC 2-Pager](https://docs.google.com/document/d/1r28pv2tJXdcfIuKT_6P2fCHM5Fjqw7czRF3ljqjqFf0/edit) created in 2021

**Comment by tschaffter** [comment]
Depends on #663

**Comment by tschaffter** [comment]
Thomas to review 2-pager previously created and then close this ticket.

**Comment by vpchung** [comment]
I reviewed the two-pager and edited what I felt comfortable with updating.

**Comment by tschaffter** [comment]
Thanks! I've started to go through the doc.

**Comment by tschaffter** [comment]
I updated the two pager minus the appendix version. If we were to share it with an organization, we can either remove the appendix to keep the document short (2 pages) or update the appendix.
