### ISSUE TITLE
Identify the list of the 5 organizations that we want to onboard first

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#935]
## Tasks

- Review [Challenge Registry: Data Source](https://docs.google.com/spreadsheets/d/1qq7bohgYq3t_bKTRUVhGsmaYhfuQLWT8ZxUGXTuFXL8/edit#gid=0)
- Identify the first 5 organizations that we want to onboard (e.g. based on their number of challenges and who we know in these orgs)

## Depends On

- #873

**Comment by tschaffter** [comment]
- Use organizations for which we already have data
- There should be already at least 5 org

**Comment by vpchung** [comment]
Existing curated efforts have been done for:

* MICCAI 
* precisionFDA
* CAFA
* CAGI
* CAMDA

We don't yet have point-of-contact persons for CAGI or CAMDA, so we can additionally curate challenges from CodaLab and Kaggle.
