### ISSUE TITLE
Add a few sort filters to the Challenge Search page using the challenge service

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#946]
Enable to sort the challenges by 'starting soon', 'closing soon', 'most starred' using real service.

depends on 
- #1157 
- #1142

**Comment by tschaffter** [comment]
## Sprint 22.12 Review

The implementation will be similar virtually the same as in the legacy app. It's preferable to have the OpenAPI description updated first, then the backend and frontend can be developed at the same time.

Sorting is one of the first task I'll be working on in Spring 23.01 now that the Challenge service has extensive code to support filters with Query DSL.

**Comment by rrchai** [comment]
convert to #1130 for UI focus

**Comment by rrchai** [comment]
reopen to change the focus to implement the service to front-end, but convert the level to "Task"
