### ISSUE TITLE
Create Figma Mockup page for Terms and Conditions

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#994]
A link to this page is currently included in the design of the footer and on the registration page.

**Comment by tschaffter** [comment]
Created a new GitHub tag: `design`

**Comment by tschaffter** [comment]
Added to Backlog

**Comment by vpchung** [comment]
[Figma template](https://www.figma.com/file/yAeIrg6Whc8Bqj2EnG4MWP/OpenChallenges?node-id=1314%3A3395&t=HgVLo3fW0cnq0pQF-0)

**Comment by tschaffter** [comment]
The mockup looks great. We could use it for the privacy policy too. I'll close this ticket and create new ones for its implementation next sprint.
