### ISSUE TITLE
Review the routes of the Challenge Registry pages

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#997]
The legacy routes were:

- `/{username}`
- `/{username}/{challenge-name}`
- `/{org-name}`
- `/{org-name}/{challenge-name}`

This design is inspired by the route design used by GitHub.

Pros:

- Enable a user to host a list of challenges. => This feature is likely not needed. It's preferable for someone to create an org, whose ownership can be changed in the future if needed instead of "hard linking" a challenge to a user. This approach also simplifies the `/<account-id>` component because we don't need to check whether the `<account-id>` is an org (and then load the org profile component) or a user (otherwise load the user profile component).

- Short(est) URLs to user and organization page (e.g. `rocc.org/dream`, `rocc.org/tschaffter`)

Cons:

- If we are not careful, a user could register the username `about`, which would interfere with our static page `rocc.org/about`. One way to control this behavior is the way we order the app route rules. In addition, we should use a dictionary of names that we want to protect for any reasons. Coming up with such a dictionary is not trivial and not 100% future proof. An alternative solution is given below.

## Proposal 1: Prefixing user and org pages

- `/user/{username}` or `/u/{username}` (second is shorter)
- `/organization/{org-name}` or `/org/{org-name}` or `/o/{org-name}` (from long to shorter)

LinkedIn use the one letter prefix. This approach does not require use to protect username and org name for the sake of protecting potential future routes.

## Proposal 2: Remove the organization name from the challenge URL

The legacy URL was:

- `/{org-name}/{challenge-name}`

Pros:

- Enable two organizations to host two challenges that have the same name. This could be useful if we were enabling organization to "fork" challenges. This feature is not useful for the challenge registry.

Cons:

- All the challenge links will be broken if an organization changes its name.
- This format is problematic when a challenge is co-organized by more than one organization.

Instead, we could use:

- `/challenge/{challenge-name}` or
- `/c/{challenge-name}` (shorter)

I have also seen the above links suffixed with a code, e.g. `/c/ehr-dream-challenge-0123456`. I need to explore what are the benefit of such format (versioning of a page or allow two different challenges to have the same name?).

**Comment by tschaffter** [comment]
Here is the latest proposal for the design of the routes of the Challenge Registry app ([Google doc](https://docs.google.com/document/d/10ttgzMBvJitqGMhn58O2b_kZMj7to6fr-JfxdqqjLog)).

@rrchai @vpchung How does this proposal sounds?

**Comment by rrchai** [comment]
Thanks @tschaffter. I prefer to have a shorter urls, `/c/{challenge-name}`, `/o/{org-name}`, `/u/{user-name}`.

**Comment by tschaffter** [comment]
The new URL design has been implemented.
